version: "3.9"
services:
  math3d_db:
    image: postgres:15.1
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=math3d_next 
    ports:
      - "5431:5432"
  
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      bash
    volumes:
      - ./webserver:/app