version: "3.9"

networks:
  default-network:
    driver: bridge

services:
  db:
    image: postgres:15.1
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=math3d 
    networks:
      default-network:
    ports:
      - "5431:5432"
  
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
        DATABASE_URL: postgresql://docker:docker@db:5432/math3d
    command: >
      python manage.py runserver
    volumes:
      - ./webserver:/src
    networks:
      default-network: