version: "3.9"

networks:
  default-network:
    driver: bridge

services:
  db:
    image: postgres:15.3
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=math3d
    networks:
      default-network:
    ports:
      - "5431:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d math3d -U docker"]
      interval: 5s
      timeout: 60s
      retries: 5
      start_period: 80s

  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.development
      - .env
    environment:
      DATABASE_URL: postgresql://docker:docker@db:5432/math3d
      CORS_ALLOWED_ORIGINS: http://localhost:3000
    command: make devserver
    volumes:
      - ./webserver:/src/webserver
    networks:
      default-network:
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
