version: "3.9"

networks:
  default-network:
    driver: bridge

services:
  db:
    image: postgres:15.1
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=math3d 
    networks:
      default-network:
    ports:
      - "5431:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d math3d -U docker"]
      interval: 5s
      timeout: 60s
      retries: 5
      start_period: 80s  
  
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
        DATABASE_URL: postgresql://docker:docker@db:5432/math3d
    command: >
      python ./webserver/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./webserver:/src/webserver
      - ./packages/mathitem-configs:/src/packages/mathitem-configs
    networks:
      default-network:
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"