# Generated by Django 4.2.7 on 2023-12-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailDeliveries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("bounces", models.PositiveIntegerField(default=0)),
                ("complaints", models.PositiveIntegerField(default=0)),
                ("last_bounce", models.DateTimeField(null=True)),
            ],
        ),
    ]
