/* tslint:disable */
/* eslint-disable */
/**
 * Math3d API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from "./configuration";
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from "axios";
import globalAxios from "axios";
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
  replaceWithSerializableTypeIfNeeded,
} from "./common";
import type { RequestArgs } from "./base";
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  BaseAPI,
  RequiredError,
  operationServerMap,
} from "./base";

export interface ActivationSchema {
  email: string;
}
export interface AssignmentObj {
  lhs: string;
  rhs: string;
  type: AssignmentObjTypeEnum;
}

export const AssignmentObjTypeEnum = {
  Assignment: "assignment",
} as const;

export type AssignmentObjTypeEnum =
  (typeof AssignmentObjTypeEnum)[keyof typeof AssignmentObjTypeEnum];

export interface AxisItem {
  id: string;
  properties: AxisProperties;
  type: AxisItemTypeEnum;
}

export const AxisItemTypeEnum = {
  Axis: "AXIS",
} as const;

export type AxisItemTypeEnum =
  (typeof AxisItemTypeEnum)[keyof typeof AxisItemTypeEnum];

export interface AxisProperties {
  axis: AxisPropertiesAxisEnum;
  calculatedVisibility: string;
  color: string;
  description: string;
  divisions: string;
  end: string;
  label: string;
  labelVisible: string;
  max: string;
  min: string;
  opacity: string;
  scale: string;
  size: string;
  start: string;
  ticksVisible: string;
  useCalculatedVisibility: boolean;
  visible: boolean;
  width: string;
  zBias: string;
  zIndex: string;
  zOrder: string;
}

export const AxisPropertiesAxisEnum = {
  X: "x",
  Y: "y",
  Z: "z",
} as const;

export type AxisPropertiesAxisEnum =
  (typeof AxisPropertiesAxisEnum)[keyof typeof AxisPropertiesAxisEnum];

export interface BooleanVariableItem {
  id: string;
  properties: BooleanVariableProperties;
  type: BooleanVariableItemTypeEnum;
}

export const BooleanVariableItemTypeEnum = {
  BooleanVariable: "BOOLEAN_VARIABLE",
} as const;

export type BooleanVariableItemTypeEnum =
  (typeof BooleanVariableItemTypeEnum)[keyof typeof BooleanVariableItemTypeEnum];

export interface BooleanVariableProperties {
  description: string;
  value: AssignmentObj;
}
export interface CameraItem {
  id: string;
  properties: CameraProperties;
  type: CameraItemTypeEnum;
}

export const CameraItemTypeEnum = {
  Camera: "CAMERA",
} as const;

export type CameraItemTypeEnum =
  (typeof CameraItemTypeEnum)[keyof typeof CameraItemTypeEnum];

export interface CameraProperties {
  description: string;
  isOrthographic: string;
  isPanEnabled: string;
  isRotateEnabled: string;
  isZoomEnabled: string;
  position: string;
  target: string;
  updateOnDrag: string;
  useRelative: string;
}
export interface DeleteAccountError {
  current_password: Array<string>;
}
export interface DeleteAccountSchema {
  current_password: string;
}
export interface ExplicitSurfaceItem {
  id: string;
  properties: ExplicitSurfaceProperties;
  type: ExplicitSurfaceItemTypeEnum;
}

export const ExplicitSurfaceItemTypeEnum = {
  ExplicitSurface: "EXPLICIT_SURFACE",
} as const;

export type ExplicitSurfaceItemTypeEnum =
  (typeof ExplicitSurfaceItemTypeEnum)[keyof typeof ExplicitSurfaceItemTypeEnum];

export interface ExplicitSurfacePolarItem {
  id: string;
  properties: ExplicitSurfacePolarProperties;
  type: ExplicitSurfacePolarItemTypeEnum;
}

export const ExplicitSurfacePolarItemTypeEnum = {
  ExplicitSurfacePolar: "EXPLICIT_SURFACE_POLAR",
} as const;

export type ExplicitSurfacePolarItemTypeEnum =
  (typeof ExplicitSurfacePolarItemTypeEnum)[keyof typeof ExplicitSurfacePolarItemTypeEnum];

export interface ExplicitSurfacePolarProperties {
  calculatedVisibility: string;
  color: string;
  colorExpr: FunctionAssignmentObj;
  description: string;
  domain: FunctionAssignmentArray;
  expr: FunctionAssignmentObj;
  grid1: string;
  grid2: string;
  gridOpacity: string;
  gridWidth: string;
  opacity: string;
  samples1: string;
  samples2: string;
  shaded: string;
  useCalculatedVisibility: boolean;
  visible: boolean;
  zBias: string;
  zIndex: string;
  zOrder: string;
}
export interface ExplicitSurfaceProperties {
  calculatedVisibility: string;
  color: string;
  colorExpr: FunctionAssignmentObj;
  description: string;
  domain: FunctionAssignmentArray;
  expr: FunctionAssignmentObj;
  grid1: string;
  grid2: string;
  gridOpacity: string;
  gridWidth: string;
  opacity: string;
  samples1: string;
  samples2: string;
  shaded: string;
  useCalculatedVisibility: boolean;
  visible: boolean;
  zBias: string;
  zIndex: string;
  zOrder: string;
}
export interface ExprArray {
  items: Array<ExprObj>;
  type: ExprArrayTypeEnum;
}

export const ExprArrayTypeEnum = {
  Array: "array",
} as const;

export type ExprArrayTypeEnum =
  (typeof ExprArrayTypeEnum)[keyof typeof ExprArrayTypeEnum];

export interface ExprObj {
  expr: string;
  type: ExprObjTypeEnum;
}

export const ExprObjTypeEnum = {
  Expr: "expr",
} as const;

export type ExprObjTypeEnum =
  (typeof ExprObjTypeEnum)[keyof typeof ExprObjTypeEnum];

export interface FolderItem {
  id: string;
  properties: FolderProperties;
  type: FolderItemTypeEnum;
}

export const FolderItemTypeEnum = {
  Folder: "FOLDER",
} as const;

export type FolderItemTypeEnum =
  (typeof FolderItemTypeEnum)[keyof typeof FolderItemTypeEnum];

export interface FolderProperties {
  description: string;
  isCollapsed: string;
}
export interface FunctionAssignmentArray {
  items: Array<FunctionAssignmentObj>;
  type: FunctionAssignmentArrayTypeEnum;
}

export const FunctionAssignmentArrayTypeEnum = {
  Array: "array",
} as const;

export type FunctionAssignmentArrayTypeEnum =
  (typeof FunctionAssignmentArrayTypeEnum)[keyof typeof FunctionAssignmentArrayTypeEnum];

export interface FunctionAssignmentObj {
  name: string;
  params: Array<string>;
  rhs: string;
  type: FunctionAssignmentObjTypeEnum;
}

export const FunctionAssignmentObjTypeEnum = {
  FunctionAssignment: "function-assignment",
} as const;

export type FunctionAssignmentObjTypeEnum =
  (typeof FunctionAssignmentObjTypeEnum)[keyof typeof FunctionAssignmentObjTypeEnum];

export interface GridItem {
  id: string;
  properties: GridProperties;
  type: GridItemTypeEnum;
}

export const GridItemTypeEnum = {
  Grid: "GRID",
} as const;

export type GridItemTypeEnum =
  (typeof GridItemTypeEnum)[keyof typeof GridItemTypeEnum];

export interface GridProperties {
  axes: GridPropertiesAxesEnum;
  calculatedVisibility: string;
  color: string;
  description: string;
  divisions: string;
  opacity: string;
  snap: string;
  useCalculatedVisibility: boolean;
  visible: boolean;
  width: string;
  zBias: string;
  zIndex: string;
  zOrder: string;
}

export const GridPropertiesAxesEnum = {
  Xy: "xy",
  Yz: "yz",
  Zx: "zx",
} as const;

export type GridPropertiesAxesEnum =
  (typeof GridPropertiesAxesEnum)[keyof typeof GridPropertiesAxesEnum];

export interface ImplicitSurfaceItem {
  id: string;
  properties: ImplicitSurfaceProperties;
  type: ImplicitSurfaceItemTypeEnum;
}

export const ImplicitSurfaceItemTypeEnum = {
  ImplicitSurface: "IMPLICIT_SURFACE",
} as const;

export type ImplicitSurfaceItemTypeEnum =
  (typeof ImplicitSurfaceItemTypeEnum)[keyof typeof ImplicitSurfaceItemTypeEnum];

export interface ImplicitSurfaceProperties {
  calculatedVisibility: string;
  color: string;
  description: string;
  domain: ExprArray;
  lhs: FunctionAssignmentObj;
  opacity: string;
  rhs: FunctionAssignmentObj;
  samples: string;
  shaded: string;
  useCalculatedVisibility: boolean;
  visible: boolean;
  zBias: string;
  zIndex: string;
  zOrder: string;
}
export interface Input {
  limit?: number;
  offset?: number;
}
export interface LegacySceneInSchema {
  dehydrated: any;
}
export interface LegacySceneOutSchema {
  dehydrated: any;
  key: string;
}
export interface LineItem {
  id: string;
  properties: LineProperties;
  type: LineItemTypeEnum;
}

export const LineItemTypeEnum = {
  Line: "LINE",
} as const;

export type LineItemTypeEnum =
  (typeof LineItemTypeEnum)[keyof typeof LineItemTypeEnum];

export interface LineProperties {
  calculatedVisibility: string;
  color: string;
  coords: string;
  description: string;
  end: string;
  label: string;
  labelVisible: string;
  opacity: string;
  size: string;
  start: string;
  useCalculatedVisibility: boolean;
  visible: boolean;
  width: string;
  zBias: string;
  zIndex: string;
  zOrder: string;
}
/**
 * @type MathItem
 */
export type MathItem =
  | ({ type: "AXIS" } & AxisItem)
  | ({ type: "BOOLEAN_VARIABLE" } & BooleanVariableItem)
  | ({ type: "CAMERA" } & CameraItem)
  | ({ type: "EXPLICIT_SURFACE" } & ExplicitSurfaceItem)
  | ({ type: "EXPLICIT_SURFACE_POLAR" } & ExplicitSurfacePolarItem)
  | ({ type: "FOLDER" } & FolderItem)
  | ({ type: "GRID" } & GridItem)
  | ({ type: "IMPLICIT_SURFACE" } & ImplicitSurfaceItem)
  | ({ type: "LINE" } & LineItem)
  | ({ type: "PARAMETRIC_CURVE" } & ParametricCurveItem)
  | ({ type: "PARAMETRIC_SURFACE" } & ParametricSurfaceItem)
  | ({ type: "POINT" } & PointItem)
  | ({ type: "VARIABLE" } & VariableItem)
  | ({ type: "VARIABLE_SLIDER" } & VariableSliderItem)
  | ({ type: "VECTOR" } & VectorItem)
  | ({ type: "VECTOR_FIELD" } & VectorFieldItem);

export interface MiniSceneSchema {
  archived: boolean;
  author?: number | null;
  createdDate: string;
  key: string;
  modifiedDate: string;
  title?: string | null;
}
export interface PagedMiniSceneSchema {
  count: number;
  items: Array<MiniSceneSchema>;
}
export interface ParametricCurveItem {
  id: string;
  properties: ParametricCurveProperties;
  type: ParametricCurveItemTypeEnum;
}

export const ParametricCurveItemTypeEnum = {
  ParametricCurve: "PARAMETRIC_CURVE",
} as const;

export type ParametricCurveItemTypeEnum =
  (typeof ParametricCurveItemTypeEnum)[keyof typeof ParametricCurveItemTypeEnum];

export interface ParametricCurveProperties {
  calculatedVisibility: string;
  color: string;
  description: string;
  domain: ExprArray;
  end: string;
  expr: FunctionAssignmentObj;
  opacity: string;
  samples1: string;
  size: string;
  start: string;
  useCalculatedVisibility: boolean;
  visible: boolean;
  width: string;
  zBias: string;
  zIndex: string;
  zOrder: string;
}
export interface ParametricSurfaceItem {
  id: string;
  properties: ParametricSurfaceProperties;
  type: ParametricSurfaceItemTypeEnum;
}

export const ParametricSurfaceItemTypeEnum = {
  ParametricSurface: "PARAMETRIC_SURFACE",
} as const;

export type ParametricSurfaceItemTypeEnum =
  (typeof ParametricSurfaceItemTypeEnum)[keyof typeof ParametricSurfaceItemTypeEnum];

export interface ParametricSurfaceProperties {
  calculatedVisibility: string;
  color: string;
  colorExpr: FunctionAssignmentObj;
  description: string;
  domain: FunctionAssignmentArray;
  expr: FunctionAssignmentObj;
  grid1: string;
  grid2: string;
  gridOpacity: string;
  gridWidth: string;
  opacity: string;
  samples1: string;
  samples2: string;
  shaded: string;
  useCalculatedVisibility: boolean;
  visible: boolean;
  zBias: string;
  zIndex: string;
  zOrder: string;
}
export interface PointItem {
  id: string;
  properties: PointProperties;
  type: PointItemTypeEnum;
}

export const PointItemTypeEnum = {
  Point: "POINT",
} as const;

export type PointItemTypeEnum =
  (typeof PointItemTypeEnum)[keyof typeof PointItemTypeEnum];

export interface PointProperties {
  calculatedVisibility: string;
  color: string;
  coords: string;
  description: string;
  label: string;
  labelVisible: string;
  opacity: string;
  size: string;
  useCalculatedVisibility: boolean;
  visible: boolean;
  zBias: string;
  zIndex: string;
  zOrder: string;
}
export interface SceneCreateSchema {
  archived?: boolean;
  itemOrder: { [key: string]: Array<string> };
  items: Array<MathItem>;
  title?: string | null;
}
export interface SceneFilterSchema {
  archived?: boolean | null;
  title?: string | null;
}
export interface ScenePatchSchema {
  archived?: boolean | null;
  itemOrder?: { [key: string]: Array<string> };
  items?: Array<MathItem>;
  title?: string | null;
}
export interface SceneSchema {
  archived: boolean;
  author?: number | null;
  createdDate: string;
  isLegacy: boolean;
  itemOrder: { [key: string]: Array<string> };
  items: Array<MathItem>;
  key: string;
  modifiedDate: string;
  title?: string | null;
}
export interface StrArray {
  items: Array<string>;
  type: StrArrayTypeEnum;
}

export const StrArrayTypeEnum = {
  Array: "array",
} as const;

export type StrArrayTypeEnum =
  (typeof StrArrayTypeEnum)[keyof typeof StrArrayTypeEnum];

export interface UserSchema {
  email: string;
  id: number;
  public_nickname: string;
}
export interface UserUpdateSchema {
  public_nickname: string;
}
export interface VariableItem {
  id: string;
  properties: VariableProperties;
  type: VariableItemTypeEnum;
}

export const VariableItemTypeEnum = {
  Variable: "VARIABLE",
} as const;

export type VariableItemTypeEnum =
  (typeof VariableItemTypeEnum)[keyof typeof VariableItemTypeEnum];

export interface VariableProperties {
  description: string;
  value: AssignmentObj;
}
export interface VariableSliderItem {
  id: string;
  properties: VariableSliderProperties;
  type: VariableSliderItemTypeEnum;
}

export const VariableSliderItemTypeEnum = {
  VariableSlider: "VARIABLE_SLIDER",
} as const;

export type VariableSliderItemTypeEnum =
  (typeof VariableSliderItemTypeEnum)[keyof typeof VariableSliderItemTypeEnum];

export interface VariableSliderProperties {
  description: string;
  duration: string;
  fps: string;
  isAnimating: string;
  range: StrArray;
  speedMultiplier: string;
  value: AssignmentObj;
}
export interface VectorFieldItem {
  id: string;
  properties: VectorFieldProperties;
  type: VectorFieldItemTypeEnum;
}

export const VectorFieldItemTypeEnum = {
  VectorField: "VECTOR_FIELD",
} as const;

export type VectorFieldItemTypeEnum =
  (typeof VectorFieldItemTypeEnum)[keyof typeof VectorFieldItemTypeEnum];

export interface VectorFieldProperties {
  calculatedVisibility: string;
  color: string;
  description: string;
  domain: ExprArray;
  end: string;
  expr: FunctionAssignmentObj;
  opacity: string;
  samples1: string;
  samples2: string;
  samples3: string;
  scale: string;
  size: string;
  start: string;
  useCalculatedVisibility: boolean;
  visible: boolean;
  width: string;
  zBias: string;
  zIndex: string;
  zOrder: string;
}
export interface VectorItem {
  id: string;
  properties: VectorProperties;
  type: VectorItemTypeEnum;
}

export const VectorItemTypeEnum = {
  Vector: "VECTOR",
} as const;

export type VectorItemTypeEnum =
  (typeof VectorItemTypeEnum)[keyof typeof VectorItemTypeEnum];

export interface VectorProperties {
  calculatedVisibility: string;
  color: string;
  components: string;
  description: string;
  end: string;
  label: string;
  labelVisible: string;
  opacity: string;
  size: string;
  start: string;
  tail: string;
  useCalculatedVisibility: boolean;
  visible: boolean;
  width: string;
  zBias: string;
  zIndex: string;
  zOrder: string;
}

/**
 * DefaultApi - axios parameter creator
 */
export const DefaultApiAxiosParamCreator = function (
  configuration?: Configuration,
) {
  return {
    /**
     *
     * @summary Activate
     * @param {ActivationSchema} ActivationSchema
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    authenticationApiActivate: async (
      ActivationSchema: ActivationSchema,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'ActivationSchema' is not null or undefined
      assertParamExists(
        "authenticationApiActivate",
        "ActivationSchema",
        ActivationSchema,
      );
      const localVarPath = `/v1/auth/users/activation/`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication StaffSessionAuth required

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        ActivationSchema,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Delete Me
     * @param {DeleteAccountSchema} DeleteAccountSchema
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    authenticationApiDeleteMe: async (
      DeleteAccountSchema: DeleteAccountSchema,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'DeleteAccountSchema' is not null or undefined
      assertParamExists(
        "authenticationApiDeleteMe",
        "DeleteAccountSchema",
        DeleteAccountSchema,
      );
      const localVarPath = `/v1/auth/users/me/delete/`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication SessionAuth required

      localVarHeaderParameter["Content-Type"] = "application/json";
      localVarHeaderParameter["Accept"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        DeleteAccountSchema,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Get Me
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    authenticationApiGetMe: async (
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/v1/auth/users/me/`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Accept"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Patch Me
     * @param {UserUpdateSchema} UserUpdateSchema
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    authenticationApiPatchMe: async (
      UserUpdateSchema: UserUpdateSchema,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'UserUpdateSchema' is not null or undefined
      assertParamExists(
        "authenticationApiPatchMe",
        "UserUpdateSchema",
        UserUpdateSchema,
      );
      const localVarPath = `/v1/auth/users/me/`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "PATCH",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication SessionAuth required

      localVarHeaderParameter["Content-Type"] = "application/json";
      localVarHeaderParameter["Accept"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        UserUpdateSchema,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Create Legacy
     * @param {LegacySceneInSchema} LegacySceneInSchema
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    scenesApiCreateLegacy: async (
      LegacySceneInSchema: LegacySceneInSchema,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'LegacySceneInSchema' is not null or undefined
      assertParamExists(
        "scenesApiCreateLegacy",
        "LegacySceneInSchema",
        LegacySceneInSchema,
      );
      const localVarPath = `/v1/legacy_scenes/`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Content-Type"] = "application/json";
      localVarHeaderParameter["Accept"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        LegacySceneInSchema,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Create Scene
     * @param {SceneCreateSchema} SceneCreateSchema
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    scenesApiCreateScene: async (
      SceneCreateSchema: SceneCreateSchema,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'SceneCreateSchema' is not null or undefined
      assertParamExists(
        "scenesApiCreateScene",
        "SceneCreateSchema",
        SceneCreateSchema,
      );
      const localVarPath = `/v1/scenes/`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Content-Type"] = "application/json";
      localVarHeaderParameter["Accept"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        SceneCreateSchema,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Delete Scene
     * @param {string} key
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    scenesApiDeleteScene: async (
      key: string,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'key' is not null or undefined
      assertParamExists("scenesApiDeleteScene", "key", key);
      const localVarPath = `/v1/scenes/{key}/`.replace(
        "{key}",
        encodeURIComponent(String(key)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "DELETE",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication SessionAuth required

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Get Legacy
     * @param {string} key
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    scenesApiGetLegacy: async (
      key: string,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'key' is not null or undefined
      assertParamExists("scenesApiGetLegacy", "key", key);
      const localVarPath = `/v1/legacy_scenes/{key}/`.replace(
        "{key}",
        encodeURIComponent(String(key)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Accept"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Get Scene
     * @param {string} key
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    scenesApiGetScene: async (
      key: string,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'key' is not null or undefined
      assertParamExists("scenesApiGetScene", "key", key);
      const localVarPath = `/v1/scenes/{key}/`.replace(
        "{key}",
        encodeURIComponent(String(key)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Accept"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary List Scenes
     * @param {string | null} [title]
     * @param {boolean | null} [archived]
     * @param {number} [limit]
     * @param {number} [offset]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    scenesApiListScenes: async (
      title?: string | null,
      archived?: boolean | null,
      limit?: number,
      offset?: number,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/v1/scenes/`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      if (title !== undefined) {
        localVarQueryParameter["title"] = title;
      }

      if (archived !== undefined) {
        localVarQueryParameter["archived"] = archived;
      }

      if (limit !== undefined) {
        localVarQueryParameter["limit"] = limit;
      }

      if (offset !== undefined) {
        localVarQueryParameter["offset"] = offset;
      }

      localVarHeaderParameter["Accept"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary My Scenes
     * @param {string | null} [title]
     * @param {boolean | null} [archived]
     * @param {number} [limit]
     * @param {number} [offset]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    scenesApiMyScenes: async (
      title?: string | null,
      archived?: boolean | null,
      limit?: number,
      offset?: number,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/v1/scenes/me/`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication SessionAuth required

      if (title !== undefined) {
        localVarQueryParameter["title"] = title;
      }

      if (archived !== undefined) {
        localVarQueryParameter["archived"] = archived;
      }

      if (limit !== undefined) {
        localVarQueryParameter["limit"] = limit;
      }

      if (offset !== undefined) {
        localVarQueryParameter["offset"] = offset;
      }

      localVarHeaderParameter["Accept"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Update Scene
     * @param {string} key
     * @param {ScenePatchSchema} ScenePatchSchema
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    scenesApiUpdateScene: async (
      key: string,
      ScenePatchSchema: ScenePatchSchema,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'key' is not null or undefined
      assertParamExists("scenesApiUpdateScene", "key", key);
      // verify required parameter 'ScenePatchSchema' is not null or undefined
      assertParamExists(
        "scenesApiUpdateScene",
        "ScenePatchSchema",
        ScenePatchSchema,
      );
      const localVarPath = `/v1/scenes/{key}/`.replace(
        "{key}",
        encodeURIComponent(String(key)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "PATCH",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication SessionAuth required

      localVarHeaderParameter["Content-Type"] = "application/json";
      localVarHeaderParameter["Accept"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        ScenePatchSchema,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * DefaultApi - functional programming interface
 */
export const DefaultApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration);
  return {
    /**
     *
     * @summary Activate
     * @param {ActivationSchema} ActivationSchema
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async authenticationApiActivate(
      ActivationSchema: ActivationSchema,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.authenticationApiActivate(
          ActivationSchema,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["DefaultApi.authenticationApiActivate"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary Delete Me
     * @param {DeleteAccountSchema} DeleteAccountSchema
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async authenticationApiDeleteMe(
      DeleteAccountSchema: DeleteAccountSchema,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.authenticationApiDeleteMe(
          DeleteAccountSchema,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["DefaultApi.authenticationApiDeleteMe"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary Get Me
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async authenticationApiGetMe(
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserSchema>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.authenticationApiGetMe(options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["DefaultApi.authenticationApiGetMe"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary Patch Me
     * @param {UserUpdateSchema} UserUpdateSchema
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async authenticationApiPatchMe(
      UserUpdateSchema: UserUpdateSchema,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserSchema>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.authenticationApiPatchMe(
          UserUpdateSchema,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["DefaultApi.authenticationApiPatchMe"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary Create Legacy
     * @param {LegacySceneInSchema} LegacySceneInSchema
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async scenesApiCreateLegacy(
      LegacySceneInSchema: LegacySceneInSchema,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<LegacySceneOutSchema>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.scenesApiCreateLegacy(
          LegacySceneInSchema,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["DefaultApi.scenesApiCreateLegacy"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary Create Scene
     * @param {SceneCreateSchema} SceneCreateSchema
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async scenesApiCreateScene(
      SceneCreateSchema: SceneCreateSchema,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<SceneSchema>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.scenesApiCreateScene(
          SceneCreateSchema,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["DefaultApi.scenesApiCreateScene"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary Delete Scene
     * @param {string} key
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async scenesApiDeleteScene(
      key: string,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.scenesApiDeleteScene(key, options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["DefaultApi.scenesApiDeleteScene"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary Get Legacy
     * @param {string} key
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async scenesApiGetLegacy(
      key: string,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<LegacySceneOutSchema>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.scenesApiGetLegacy(key, options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["DefaultApi.scenesApiGetLegacy"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary Get Scene
     * @param {string} key
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async scenesApiGetScene(
      key: string,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<SceneSchema>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.scenesApiGetScene(key, options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["DefaultApi.scenesApiGetScene"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary List Scenes
     * @param {string | null} [title]
     * @param {boolean | null} [archived]
     * @param {number} [limit]
     * @param {number} [offset]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async scenesApiListScenes(
      title?: string | null,
      archived?: boolean | null,
      limit?: number,
      offset?: number,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<PagedMiniSceneSchema>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.scenesApiListScenes(
          title,
          archived,
          limit,
          offset,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["DefaultApi.scenesApiListScenes"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary My Scenes
     * @param {string | null} [title]
     * @param {boolean | null} [archived]
     * @param {number} [limit]
     * @param {number} [offset]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async scenesApiMyScenes(
      title?: string | null,
      archived?: boolean | null,
      limit?: number,
      offset?: number,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<PagedMiniSceneSchema>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.scenesApiMyScenes(
          title,
          archived,
          limit,
          offset,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["DefaultApi.scenesApiMyScenes"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary Update Scene
     * @param {string} key
     * @param {ScenePatchSchema} ScenePatchSchema
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async scenesApiUpdateScene(
      key: string,
      ScenePatchSchema: ScenePatchSchema,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<SceneSchema>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.scenesApiUpdateScene(
          key,
          ScenePatchSchema,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["DefaultApi.scenesApiUpdateScene"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
  };
};

/**
 * DefaultApi - factory interface
 */
export const DefaultApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = DefaultApiFp(configuration);
  return {
    /**
     *
     * @summary Activate
     * @param {DefaultApiAuthenticationApiActivateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    authenticationApiActivate(
      requestParameters: DefaultApiAuthenticationApiActivateRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<void> {
      return localVarFp
        .authenticationApiActivate(requestParameters.ActivationSchema, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Delete Me
     * @param {DefaultApiAuthenticationApiDeleteMeRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    authenticationApiDeleteMe(
      requestParameters: DefaultApiAuthenticationApiDeleteMeRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<void> {
      return localVarFp
        .authenticationApiDeleteMe(
          requestParameters.DeleteAccountSchema,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Get Me
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    authenticationApiGetMe(
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<UserSchema> {
      return localVarFp
        .authenticationApiGetMe(options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Patch Me
     * @param {DefaultApiAuthenticationApiPatchMeRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    authenticationApiPatchMe(
      requestParameters: DefaultApiAuthenticationApiPatchMeRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<UserSchema> {
      return localVarFp
        .authenticationApiPatchMe(requestParameters.UserUpdateSchema, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Create Legacy
     * @param {DefaultApiScenesApiCreateLegacyRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    scenesApiCreateLegacy(
      requestParameters: DefaultApiScenesApiCreateLegacyRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<LegacySceneOutSchema> {
      return localVarFp
        .scenesApiCreateLegacy(requestParameters.LegacySceneInSchema, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Create Scene
     * @param {DefaultApiScenesApiCreateSceneRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    scenesApiCreateScene(
      requestParameters: DefaultApiScenesApiCreateSceneRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<SceneSchema> {
      return localVarFp
        .scenesApiCreateScene(requestParameters.SceneCreateSchema, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Delete Scene
     * @param {DefaultApiScenesApiDeleteSceneRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    scenesApiDeleteScene(
      requestParameters: DefaultApiScenesApiDeleteSceneRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<void> {
      return localVarFp
        .scenesApiDeleteScene(requestParameters.key, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Get Legacy
     * @param {DefaultApiScenesApiGetLegacyRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    scenesApiGetLegacy(
      requestParameters: DefaultApiScenesApiGetLegacyRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<LegacySceneOutSchema> {
      return localVarFp
        .scenesApiGetLegacy(requestParameters.key, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Get Scene
     * @param {DefaultApiScenesApiGetSceneRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    scenesApiGetScene(
      requestParameters: DefaultApiScenesApiGetSceneRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<SceneSchema> {
      return localVarFp
        .scenesApiGetScene(requestParameters.key, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary List Scenes
     * @param {DefaultApiScenesApiListScenesRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    scenesApiListScenes(
      requestParameters: DefaultApiScenesApiListScenesRequest = {},
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<PagedMiniSceneSchema> {
      return localVarFp
        .scenesApiListScenes(
          requestParameters.title,
          requestParameters.archived,
          requestParameters.limit,
          requestParameters.offset,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary My Scenes
     * @param {DefaultApiScenesApiMyScenesRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    scenesApiMyScenes(
      requestParameters: DefaultApiScenesApiMyScenesRequest = {},
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<PagedMiniSceneSchema> {
      return localVarFp
        .scenesApiMyScenes(
          requestParameters.title,
          requestParameters.archived,
          requestParameters.limit,
          requestParameters.offset,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Update Scene
     * @param {DefaultApiScenesApiUpdateSceneRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    scenesApiUpdateScene(
      requestParameters: DefaultApiScenesApiUpdateSceneRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<SceneSchema> {
      return localVarFp
        .scenesApiUpdateScene(
          requestParameters.key,
          requestParameters.ScenePatchSchema,
          options,
        )
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * Request parameters for authenticationApiActivate operation in DefaultApi.
 */
export interface DefaultApiAuthenticationApiActivateRequest {
  readonly ActivationSchema: ActivationSchema;
}

/**
 * Request parameters for authenticationApiDeleteMe operation in DefaultApi.
 */
export interface DefaultApiAuthenticationApiDeleteMeRequest {
  readonly DeleteAccountSchema: DeleteAccountSchema;
}

/**
 * Request parameters for authenticationApiPatchMe operation in DefaultApi.
 */
export interface DefaultApiAuthenticationApiPatchMeRequest {
  readonly UserUpdateSchema: UserUpdateSchema;
}

/**
 * Request parameters for scenesApiCreateLegacy operation in DefaultApi.
 */
export interface DefaultApiScenesApiCreateLegacyRequest {
  readonly LegacySceneInSchema: LegacySceneInSchema;
}

/**
 * Request parameters for scenesApiCreateScene operation in DefaultApi.
 */
export interface DefaultApiScenesApiCreateSceneRequest {
  readonly SceneCreateSchema: SceneCreateSchema;
}

/**
 * Request parameters for scenesApiDeleteScene operation in DefaultApi.
 */
export interface DefaultApiScenesApiDeleteSceneRequest {
  readonly key: string;
}

/**
 * Request parameters for scenesApiGetLegacy operation in DefaultApi.
 */
export interface DefaultApiScenesApiGetLegacyRequest {
  readonly key: string;
}

/**
 * Request parameters for scenesApiGetScene operation in DefaultApi.
 */
export interface DefaultApiScenesApiGetSceneRequest {
  readonly key: string;
}

/**
 * Request parameters for scenesApiListScenes operation in DefaultApi.
 */
export interface DefaultApiScenesApiListScenesRequest {
  readonly title?: string | null;

  readonly archived?: boolean | null;

  readonly limit?: number;

  readonly offset?: number;
}

/**
 * Request parameters for scenesApiMyScenes operation in DefaultApi.
 */
export interface DefaultApiScenesApiMyScenesRequest {
  readonly title?: string | null;

  readonly archived?: boolean | null;

  readonly limit?: number;

  readonly offset?: number;
}

/**
 * Request parameters for scenesApiUpdateScene operation in DefaultApi.
 */
export interface DefaultApiScenesApiUpdateSceneRequest {
  readonly key: string;

  readonly ScenePatchSchema: ScenePatchSchema;
}

/**
 * DefaultApi - object-oriented interface
 */
export class DefaultApi extends BaseAPI {
  /**
   *
   * @summary Activate
   * @param {DefaultApiAuthenticationApiActivateRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public authenticationApiActivate(
    requestParameters: DefaultApiAuthenticationApiActivateRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return DefaultApiFp(this.configuration)
      .authenticationApiActivate(requestParameters.ActivationSchema, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Delete Me
   * @param {DefaultApiAuthenticationApiDeleteMeRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public authenticationApiDeleteMe(
    requestParameters: DefaultApiAuthenticationApiDeleteMeRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return DefaultApiFp(this.configuration)
      .authenticationApiDeleteMe(requestParameters.DeleteAccountSchema, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Get Me
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public authenticationApiGetMe(options?: RawAxiosRequestConfig) {
    return DefaultApiFp(this.configuration)
      .authenticationApiGetMe(options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Patch Me
   * @param {DefaultApiAuthenticationApiPatchMeRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public authenticationApiPatchMe(
    requestParameters: DefaultApiAuthenticationApiPatchMeRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return DefaultApiFp(this.configuration)
      .authenticationApiPatchMe(requestParameters.UserUpdateSchema, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Create Legacy
   * @param {DefaultApiScenesApiCreateLegacyRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public scenesApiCreateLegacy(
    requestParameters: DefaultApiScenesApiCreateLegacyRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return DefaultApiFp(this.configuration)
      .scenesApiCreateLegacy(requestParameters.LegacySceneInSchema, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Create Scene
   * @param {DefaultApiScenesApiCreateSceneRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public scenesApiCreateScene(
    requestParameters: DefaultApiScenesApiCreateSceneRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return DefaultApiFp(this.configuration)
      .scenesApiCreateScene(requestParameters.SceneCreateSchema, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Delete Scene
   * @param {DefaultApiScenesApiDeleteSceneRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public scenesApiDeleteScene(
    requestParameters: DefaultApiScenesApiDeleteSceneRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return DefaultApiFp(this.configuration)
      .scenesApiDeleteScene(requestParameters.key, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Get Legacy
   * @param {DefaultApiScenesApiGetLegacyRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public scenesApiGetLegacy(
    requestParameters: DefaultApiScenesApiGetLegacyRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return DefaultApiFp(this.configuration)
      .scenesApiGetLegacy(requestParameters.key, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Get Scene
   * @param {DefaultApiScenesApiGetSceneRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public scenesApiGetScene(
    requestParameters: DefaultApiScenesApiGetSceneRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return DefaultApiFp(this.configuration)
      .scenesApiGetScene(requestParameters.key, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary List Scenes
   * @param {DefaultApiScenesApiListScenesRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public scenesApiListScenes(
    requestParameters: DefaultApiScenesApiListScenesRequest = {},
    options?: RawAxiosRequestConfig,
  ) {
    return DefaultApiFp(this.configuration)
      .scenesApiListScenes(
        requestParameters.title,
        requestParameters.archived,
        requestParameters.limit,
        requestParameters.offset,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary My Scenes
   * @param {DefaultApiScenesApiMyScenesRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public scenesApiMyScenes(
    requestParameters: DefaultApiScenesApiMyScenesRequest = {},
    options?: RawAxiosRequestConfig,
  ) {
    return DefaultApiFp(this.configuration)
      .scenesApiMyScenes(
        requestParameters.title,
        requestParameters.archived,
        requestParameters.limit,
        requestParameters.offset,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Update Scene
   * @param {DefaultApiScenesApiUpdateSceneRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public scenesApiUpdateScene(
    requestParameters: DefaultApiScenesApiUpdateSceneRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return DefaultApiFp(this.configuration)
      .scenesApiUpdateScene(
        requestParameters.key,
        requestParameters.ScenePatchSchema,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }
}
