/* tslint:disable */
/* eslint-disable */
/**
 * Math3d API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from "./configuration";
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from "axios";
import globalAxios from "axios";
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from "./common";
import type { RequestArgs } from "./base";
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  BaseAPI,
  RequiredError,
  operationServerMap,
} from "./base";

/**
 *
 * @export
 * @interface ActivationSchema
 */
export interface ActivationSchema {
  /**
   *
   * @type {string}
   * @memberof ActivationSchema
   */
  email: string;
}
/**
 *
 * @export
 * @interface DeleteAccountError
 */
export interface DeleteAccountError {
  /**
   *
   * @type {Array<string>}
   * @memberof DeleteAccountError
   */
  current_password: Array<string>;
}
/**
 *
 * @export
 * @interface DeleteAccountSchema
 */
export interface DeleteAccountSchema {
  /**
   *
   * @type {string}
   * @memberof DeleteAccountSchema
   */
  current_password: string;
}
/**
 *
 * @export
 * @interface Input
 */
export interface Input {
  /**
   *
   * @type {number}
   * @memberof Input
   */
  limit?: number;
  /**
   *
   * @type {number}
   * @memberof Input
   */
  offset?: number;
}
/**
 *
 * @export
 * @interface LegacySceneInSchema
 */
export interface LegacySceneInSchema {
  /**
   *
   * @type {any}
   * @memberof LegacySceneInSchema
   */
  dehydrated: any;
}
/**
 *
 * @export
 * @interface LegacySceneOutSchema
 */
export interface LegacySceneOutSchema {
  /**
   *
   * @type {any}
   * @memberof LegacySceneOutSchema
   */
  dehydrated: any;
  /**
   *
   * @type {string}
   * @memberof LegacySceneOutSchema
   */
  key: string;
}
/**
 *
 * @export
 * @interface MiniSceneSchema
 */
export interface MiniSceneSchema {
  /**
   *
   * @type {boolean}
   * @memberof MiniSceneSchema
   */
  archived: boolean;
  /**
   *
   * @type {number}
   * @memberof MiniSceneSchema
   */
  author?: number | null;
  /**
   *
   * @type {string}
   * @memberof MiniSceneSchema
   */
  createdDate: string;
  /**
   *
   * @type {string}
   * @memberof MiniSceneSchema
   */
  key: string;
  /**
   *
   * @type {string}
   * @memberof MiniSceneSchema
   */
  modifiedDate: string;
  /**
   *
   * @type {string}
   * @memberof MiniSceneSchema
   */
  title?: string | null;
}
/**
 *
 * @export
 * @interface PagedMiniSceneSchema
 */
export interface PagedMiniSceneSchema {
  /**
   *
   * @type {number}
   * @memberof PagedMiniSceneSchema
   */
  count: number;
  /**
   *
   * @type {Array<MiniSceneSchema>}
   * @memberof PagedMiniSceneSchema
   */
  items: Array<MiniSceneSchema>;
}
/**
 *
 * @export
 * @interface SceneFilterSchema
 */
export interface SceneFilterSchema {
  /**
   *
   * @type {boolean}
   * @memberof SceneFilterSchema
   */
  archived?: boolean | null;
  /**
   *
   * @type {string}
   * @memberof SceneFilterSchema
   */
  title?: string | null;
}
/**
 *
 * @export
 * @interface UserSchema
 */
export interface UserSchema {
  /**
   *
   * @type {string}
   * @memberof UserSchema
   */
  email: string;
  /**
   *
   * @type {number}
   * @memberof UserSchema
   */
  id: number;
  /**
   *
   * @type {string}
   * @memberof UserSchema
   */
  public_nickname: string;
}
/**
 *
 * @export
 * @interface UserUpdateSchema
 */
export interface UserUpdateSchema {
  /**
   *
   * @type {string}
   * @memberof UserUpdateSchema
   */
  public_nickname: string;
}

/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (
  configuration?: Configuration,
) {
  return {
    /**
     *
     * @summary Activate
     * @param {ActivationSchema} ActivationSchema
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    authenticationApiActivate: async (
      ActivationSchema: ActivationSchema,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'ActivationSchema' is not null or undefined
      assertParamExists(
        "authenticationApiActivate",
        "ActivationSchema",
        ActivationSchema,
      );
      const localVarPath = `/v1/auth/users/activation/`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication StaffSessionAuth required

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        ActivationSchema,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Delete Me
     * @param {DeleteAccountSchema} DeleteAccountSchema
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    authenticationApiDeleteMe: async (
      DeleteAccountSchema: DeleteAccountSchema,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'DeleteAccountSchema' is not null or undefined
      assertParamExists(
        "authenticationApiDeleteMe",
        "DeleteAccountSchema",
        DeleteAccountSchema,
      );
      const localVarPath = `/v1/auth/users/me/delete/`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication SessionAuth required

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        DeleteAccountSchema,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Get Me
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    authenticationApiGetMe: async (
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/v1/auth/users/me/`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication SessionAuth required

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Patch Me
     * @param {UserUpdateSchema} UserUpdateSchema
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    authenticationApiPatchMe: async (
      UserUpdateSchema: UserUpdateSchema,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'UserUpdateSchema' is not null or undefined
      assertParamExists(
        "authenticationApiPatchMe",
        "UserUpdateSchema",
        UserUpdateSchema,
      );
      const localVarPath = `/v1/auth/users/me/`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "PATCH",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication SessionAuth required

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        UserUpdateSchema,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Create Legacy
     * @param {LegacySceneInSchema} LegacySceneInSchema
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    scenesApiCreateLegacy: async (
      LegacySceneInSchema: LegacySceneInSchema,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'LegacySceneInSchema' is not null or undefined
      assertParamExists(
        "scenesApiCreateLegacy",
        "LegacySceneInSchema",
        LegacySceneInSchema,
      );
      const localVarPath = `/v1/legacy_scenes/`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        LegacySceneInSchema,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Get Legacy
     * @param {string} key
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    scenesApiGetLegacy: async (
      key: string,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'key' is not null or undefined
      assertParamExists("scenesApiGetLegacy", "key", key);
      const localVarPath = `/v1/legacy_scenes/{key}/`.replace(
        `{${"key"}}`,
        encodeURIComponent(String(key)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary List Scenes
     * @param {string | null} [title]
     * @param {boolean | null} [archived]
     * @param {number} [limit]
     * @param {number} [offset]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    scenesApiListScenes: async (
      title?: string | null,
      archived?: boolean | null,
      limit?: number,
      offset?: number,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/v1/scenes/`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      if (title !== undefined) {
        localVarQueryParameter["title"] = title;
      }

      if (archived !== undefined) {
        localVarQueryParameter["archived"] = archived;
      }

      if (limit !== undefined) {
        localVarQueryParameter["limit"] = limit;
      }

      if (offset !== undefined) {
        localVarQueryParameter["offset"] = offset;
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary My Scenes
     * @param {string | null} [title]
     * @param {boolean | null} [archived]
     * @param {number} [limit]
     * @param {number} [offset]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    scenesApiMyScenes: async (
      title?: string | null,
      archived?: boolean | null,
      limit?: number,
      offset?: number,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/v1/scenes/me/`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication SessionAuth required

      if (title !== undefined) {
        localVarQueryParameter["title"] = title;
      }

      if (archived !== undefined) {
        localVarQueryParameter["archived"] = archived;
      }

      if (limit !== undefined) {
        localVarQueryParameter["limit"] = limit;
      }

      if (offset !== undefined) {
        localVarQueryParameter["offset"] = offset;
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration);
  return {
    /**
     *
     * @summary Activate
     * @param {ActivationSchema} ActivationSchema
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async authenticationApiActivate(
      ActivationSchema: ActivationSchema,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.authenticationApiActivate(
          ActivationSchema,
          options,
        );
      const index = configuration?.serverIndex ?? 0;
      const operationBasePath =
        operationServerMap["DefaultApi.authenticationApiActivate"]?.[index]
          ?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, operationBasePath || basePath);
    },
    /**
     *
     * @summary Delete Me
     * @param {DeleteAccountSchema} DeleteAccountSchema
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async authenticationApiDeleteMe(
      DeleteAccountSchema: DeleteAccountSchema,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.authenticationApiDeleteMe(
          DeleteAccountSchema,
          options,
        );
      const index = configuration?.serverIndex ?? 0;
      const operationBasePath =
        operationServerMap["DefaultApi.authenticationApiDeleteMe"]?.[index]
          ?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, operationBasePath || basePath);
    },
    /**
     *
     * @summary Get Me
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async authenticationApiGetMe(
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserSchema>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.authenticationApiGetMe(options);
      const index = configuration?.serverIndex ?? 0;
      const operationBasePath =
        operationServerMap["DefaultApi.authenticationApiGetMe"]?.[index]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, operationBasePath || basePath);
    },
    /**
     *
     * @summary Patch Me
     * @param {UserUpdateSchema} UserUpdateSchema
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async authenticationApiPatchMe(
      UserUpdateSchema: UserUpdateSchema,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserSchema>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.authenticationApiPatchMe(
          UserUpdateSchema,
          options,
        );
      const index = configuration?.serverIndex ?? 0;
      const operationBasePath =
        operationServerMap["DefaultApi.authenticationApiPatchMe"]?.[index]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, operationBasePath || basePath);
    },
    /**
     *
     * @summary Create Legacy
     * @param {LegacySceneInSchema} LegacySceneInSchema
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async scenesApiCreateLegacy(
      LegacySceneInSchema: LegacySceneInSchema,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<LegacySceneOutSchema>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.scenesApiCreateLegacy(
          LegacySceneInSchema,
          options,
        );
      const index = configuration?.serverIndex ?? 0;
      const operationBasePath =
        operationServerMap["DefaultApi.scenesApiCreateLegacy"]?.[index]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, operationBasePath || basePath);
    },
    /**
     *
     * @summary Get Legacy
     * @param {string} key
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async scenesApiGetLegacy(
      key: string,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<LegacySceneOutSchema>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.scenesApiGetLegacy(key, options);
      const index = configuration?.serverIndex ?? 0;
      const operationBasePath =
        operationServerMap["DefaultApi.scenesApiGetLegacy"]?.[index]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, operationBasePath || basePath);
    },
    /**
     *
     * @summary List Scenes
     * @param {string | null} [title]
     * @param {boolean | null} [archived]
     * @param {number} [limit]
     * @param {number} [offset]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async scenesApiListScenes(
      title?: string | null,
      archived?: boolean | null,
      limit?: number,
      offset?: number,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<PagedMiniSceneSchema>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.scenesApiListScenes(
          title,
          archived,
          limit,
          offset,
          options,
        );
      const index = configuration?.serverIndex ?? 0;
      const operationBasePath =
        operationServerMap["DefaultApi.scenesApiListScenes"]?.[index]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, operationBasePath || basePath);
    },
    /**
     *
     * @summary My Scenes
     * @param {string | null} [title]
     * @param {boolean | null} [archived]
     * @param {number} [limit]
     * @param {number} [offset]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async scenesApiMyScenes(
      title?: string | null,
      archived?: boolean | null,
      limit?: number,
      offset?: number,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<PagedMiniSceneSchema>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.scenesApiMyScenes(
          title,
          archived,
          limit,
          offset,
          options,
        );
      const index = configuration?.serverIndex ?? 0;
      const operationBasePath =
        operationServerMap["DefaultApi.scenesApiMyScenes"]?.[index]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, operationBasePath || basePath);
    },
  };
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = DefaultApiFp(configuration);
  return {
    /**
     *
     * @summary Activate
     * @param {DefaultApiAuthenticationApiActivateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    authenticationApiActivate(
      requestParameters: DefaultApiAuthenticationApiActivateRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<void> {
      return localVarFp
        .authenticationApiActivate(requestParameters.ActivationSchema, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Delete Me
     * @param {DefaultApiAuthenticationApiDeleteMeRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    authenticationApiDeleteMe(
      requestParameters: DefaultApiAuthenticationApiDeleteMeRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<void> {
      return localVarFp
        .authenticationApiDeleteMe(
          requestParameters.DeleteAccountSchema,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Get Me
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    authenticationApiGetMe(
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<UserSchema> {
      return localVarFp
        .authenticationApiGetMe(options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Patch Me
     * @param {DefaultApiAuthenticationApiPatchMeRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    authenticationApiPatchMe(
      requestParameters: DefaultApiAuthenticationApiPatchMeRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<UserSchema> {
      return localVarFp
        .authenticationApiPatchMe(requestParameters.UserUpdateSchema, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Create Legacy
     * @param {DefaultApiScenesApiCreateLegacyRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    scenesApiCreateLegacy(
      requestParameters: DefaultApiScenesApiCreateLegacyRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<LegacySceneOutSchema> {
      return localVarFp
        .scenesApiCreateLegacy(requestParameters.LegacySceneInSchema, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Get Legacy
     * @param {DefaultApiScenesApiGetLegacyRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    scenesApiGetLegacy(
      requestParameters: DefaultApiScenesApiGetLegacyRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<LegacySceneOutSchema> {
      return localVarFp
        .scenesApiGetLegacy(requestParameters.key, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary List Scenes
     * @param {DefaultApiScenesApiListScenesRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    scenesApiListScenes(
      requestParameters: DefaultApiScenesApiListScenesRequest = {},
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<PagedMiniSceneSchema> {
      return localVarFp
        .scenesApiListScenes(
          requestParameters.title,
          requestParameters.archived,
          requestParameters.limit,
          requestParameters.offset,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary My Scenes
     * @param {DefaultApiScenesApiMyScenesRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    scenesApiMyScenes(
      requestParameters: DefaultApiScenesApiMyScenesRequest = {},
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<PagedMiniSceneSchema> {
      return localVarFp
        .scenesApiMyScenes(
          requestParameters.title,
          requestParameters.archived,
          requestParameters.limit,
          requestParameters.offset,
          options,
        )
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * Request parameters for authenticationApiActivate operation in DefaultApi.
 * @export
 * @interface DefaultApiAuthenticationApiActivateRequest
 */
export interface DefaultApiAuthenticationApiActivateRequest {
  /**
   *
   * @type {ActivationSchema}
   * @memberof DefaultApiAuthenticationApiActivate
   */
  readonly ActivationSchema: ActivationSchema;
}

/**
 * Request parameters for authenticationApiDeleteMe operation in DefaultApi.
 * @export
 * @interface DefaultApiAuthenticationApiDeleteMeRequest
 */
export interface DefaultApiAuthenticationApiDeleteMeRequest {
  /**
   *
   * @type {DeleteAccountSchema}
   * @memberof DefaultApiAuthenticationApiDeleteMe
   */
  readonly DeleteAccountSchema: DeleteAccountSchema;
}

/**
 * Request parameters for authenticationApiPatchMe operation in DefaultApi.
 * @export
 * @interface DefaultApiAuthenticationApiPatchMeRequest
 */
export interface DefaultApiAuthenticationApiPatchMeRequest {
  /**
   *
   * @type {UserUpdateSchema}
   * @memberof DefaultApiAuthenticationApiPatchMe
   */
  readonly UserUpdateSchema: UserUpdateSchema;
}

/**
 * Request parameters for scenesApiCreateLegacy operation in DefaultApi.
 * @export
 * @interface DefaultApiScenesApiCreateLegacyRequest
 */
export interface DefaultApiScenesApiCreateLegacyRequest {
  /**
   *
   * @type {LegacySceneInSchema}
   * @memberof DefaultApiScenesApiCreateLegacy
   */
  readonly LegacySceneInSchema: LegacySceneInSchema;
}

/**
 * Request parameters for scenesApiGetLegacy operation in DefaultApi.
 * @export
 * @interface DefaultApiScenesApiGetLegacyRequest
 */
export interface DefaultApiScenesApiGetLegacyRequest {
  /**
   *
   * @type {string}
   * @memberof DefaultApiScenesApiGetLegacy
   */
  readonly key: string;
}

/**
 * Request parameters for scenesApiListScenes operation in DefaultApi.
 * @export
 * @interface DefaultApiScenesApiListScenesRequest
 */
export interface DefaultApiScenesApiListScenesRequest {
  /**
   *
   * @type {string}
   * @memberof DefaultApiScenesApiListScenes
   */
  readonly title?: string | null;

  /**
   *
   * @type {boolean}
   * @memberof DefaultApiScenesApiListScenes
   */
  readonly archived?: boolean | null;

  /**
   *
   * @type {number}
   * @memberof DefaultApiScenesApiListScenes
   */
  readonly limit?: number;

  /**
   *
   * @type {number}
   * @memberof DefaultApiScenesApiListScenes
   */
  readonly offset?: number;
}

/**
 * Request parameters for scenesApiMyScenes operation in DefaultApi.
 * @export
 * @interface DefaultApiScenesApiMyScenesRequest
 */
export interface DefaultApiScenesApiMyScenesRequest {
  /**
   *
   * @type {string}
   * @memberof DefaultApiScenesApiMyScenes
   */
  readonly title?: string | null;

  /**
   *
   * @type {boolean}
   * @memberof DefaultApiScenesApiMyScenes
   */
  readonly archived?: boolean | null;

  /**
   *
   * @type {number}
   * @memberof DefaultApiScenesApiMyScenes
   */
  readonly limit?: number;

  /**
   *
   * @type {number}
   * @memberof DefaultApiScenesApiMyScenes
   */
  readonly offset?: number;
}

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
  /**
   *
   * @summary Activate
   * @param {DefaultApiAuthenticationApiActivateRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DefaultApi
   */
  public authenticationApiActivate(
    requestParameters: DefaultApiAuthenticationApiActivateRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return DefaultApiFp(this.configuration)
      .authenticationApiActivate(requestParameters.ActivationSchema, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Delete Me
   * @param {DefaultApiAuthenticationApiDeleteMeRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DefaultApi
   */
  public authenticationApiDeleteMe(
    requestParameters: DefaultApiAuthenticationApiDeleteMeRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return DefaultApiFp(this.configuration)
      .authenticationApiDeleteMe(requestParameters.DeleteAccountSchema, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Get Me
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DefaultApi
   */
  public authenticationApiGetMe(options?: RawAxiosRequestConfig) {
    return DefaultApiFp(this.configuration)
      .authenticationApiGetMe(options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Patch Me
   * @param {DefaultApiAuthenticationApiPatchMeRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DefaultApi
   */
  public authenticationApiPatchMe(
    requestParameters: DefaultApiAuthenticationApiPatchMeRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return DefaultApiFp(this.configuration)
      .authenticationApiPatchMe(requestParameters.UserUpdateSchema, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Create Legacy
   * @param {DefaultApiScenesApiCreateLegacyRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DefaultApi
   */
  public scenesApiCreateLegacy(
    requestParameters: DefaultApiScenesApiCreateLegacyRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return DefaultApiFp(this.configuration)
      .scenesApiCreateLegacy(requestParameters.LegacySceneInSchema, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Get Legacy
   * @param {DefaultApiScenesApiGetLegacyRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DefaultApi
   */
  public scenesApiGetLegacy(
    requestParameters: DefaultApiScenesApiGetLegacyRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return DefaultApiFp(this.configuration)
      .scenesApiGetLegacy(requestParameters.key, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary List Scenes
   * @param {DefaultApiScenesApiListScenesRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DefaultApi
   */
  public scenesApiListScenes(
    requestParameters: DefaultApiScenesApiListScenesRequest = {},
    options?: RawAxiosRequestConfig,
  ) {
    return DefaultApiFp(this.configuration)
      .scenesApiListScenes(
        requestParameters.title,
        requestParameters.archived,
        requestParameters.limit,
        requestParameters.offset,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary My Scenes
   * @param {DefaultApiScenesApiMyScenesRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DefaultApi
   */
  public scenesApiMyScenes(
    requestParameters: DefaultApiScenesApiMyScenesRequest = {},
    options?: RawAxiosRequestConfig,
  ) {
    return DefaultApiFp(this.configuration)
      .scenesApiMyScenes(
        requestParameters.title,
        requestParameters.archived,
        requestParameters.limit,
        requestParameters.offset,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }
}
