/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/v1/auth/users/activation/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Activate */
    post: operations["authentication_api_activate"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/auth/users/me/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Me */
    get: operations["authentication_api_get_me"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Patch Me */
    patch: operations["authentication_api_patch_me"];
    trace?: never;
  };
  "/v1/auth/users/me/delete/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Delete Me */
    post: operations["authentication_api_delete_me"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/legacy_scenes/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create Legacy */
    post: operations["scenes_api_create_legacy"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/legacy_scenes/{key}/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Legacy */
    get: operations["scenes_api_get_legacy"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/scenes/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Scenes */
    get: operations["scenes_api_list_scenes"];
    put?: never;
    /** Create Scene */
    post: operations["scenes_api_create_scene"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/scenes/me/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** My Scenes */
    get: operations["scenes_api_my_scenes"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/scenes/{key}/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Scene */
    get: operations["scenes_api_get_scene"];
    put?: never;
    post?: never;
    /** Delete Scene */
    delete: operations["scenes_api_delete_scene"];
    options?: never;
    head?: never;
    /** Update Scene */
    patch: operations["scenes_api_update_scene"];
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** ActivationSchema */
    ActivationSchema: {
      /** Email */
      email: string;
    };
    /** AssignmentObj */
    AssignmentObj: {
      /** Lhs */
      lhs: string;
      /** Rhs */
      rhs: string;
      /**
       * Type
       * @constant
       */
      type: "assignment";
    };
    /** AxisItem */
    AxisItem: {
      /** Id */
      id: string;
      properties: components["schemas"]["AxisProperties"];
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "AXIS";
    };
    /** AxisProperties */
    AxisProperties: {
      /**
       * Axis
       * @enum {string}
       */
      axis: "x" | "y" | "z";
      /** Calculatedvisibility */
      calculatedVisibility: string;
      /** Color */
      color: string;
      /** Description */
      description: string;
      /** Divisions */
      divisions: string;
      /** End */
      end: string;
      /** Label */
      label: string;
      /** Labelvisible */
      labelVisible: string;
      /** Max */
      max: string;
      /** Min */
      min: string;
      /** Opacity */
      opacity: string;
      /** Scale */
      scale: string;
      /** Size */
      size: string;
      /** Start */
      start: string;
      /** Ticksvisible */
      ticksVisible: string;
      /** Usecalculatedvisibility */
      useCalculatedVisibility: boolean;
      /** Visible */
      visible: boolean;
      /** Width */
      width: string;
      /** Zbias */
      zBias: string;
      /** Zindex */
      zIndex: string;
      /** Zorder */
      zOrder: string;
    };
    /** BooleanVariableItem */
    BooleanVariableItem: {
      /** Id */
      id: string;
      properties: components["schemas"]["BooleanVariableProperties"];
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "BOOLEAN_VARIABLE";
    };
    /** BooleanVariableProperties */
    BooleanVariableProperties: {
      /** Description */
      description: string;
      value: components["schemas"]["AssignmentObj"];
    };
    /** CameraItem */
    CameraItem: {
      /** Id */
      id: string;
      properties: components["schemas"]["CameraProperties"];
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "CAMERA";
    };
    /** CameraProperties */
    CameraProperties: {
      /** Description */
      description: string;
      /** Isorthographic */
      isOrthographic: string;
      /** Ispanenabled */
      isPanEnabled: string;
      /** Isrotateenabled */
      isRotateEnabled: string;
      /** Iszoomenabled */
      isZoomEnabled: string;
      /** Position */
      position: string;
      /** Target */
      target: string;
      /** Updateondrag */
      updateOnDrag: string;
      /** Userelative */
      useRelative: string;
    };
    /** DeleteAccountError */
    DeleteAccountError: {
      /** Current Password */
      current_password: string[];
    };
    /** DeleteAccountSchema */
    DeleteAccountSchema: {
      /** Current Password */
      current_password: string;
    };
    /** ExplicitSurfaceItem */
    ExplicitSurfaceItem: {
      /** Id */
      id: string;
      properties: components["schemas"]["ExplicitSurfaceProperties"];
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "EXPLICIT_SURFACE";
    };
    /** ExplicitSurfacePolarItem */
    ExplicitSurfacePolarItem: {
      /** Id */
      id: string;
      properties: components["schemas"]["ExplicitSurfacePolarProperties"];
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "EXPLICIT_SURFACE_POLAR";
    };
    /** ExplicitSurfacePolarProperties */
    ExplicitSurfacePolarProperties: {
      /** Calculatedvisibility */
      calculatedVisibility: string;
      /** Color */
      color: string;
      colorExpr: components["schemas"]["FunctionAssignmentObj"];
      /** Description */
      description: string;
      domain: components["schemas"]["FunctionAssignmentArray"];
      expr: components["schemas"]["FunctionAssignmentObj"];
      /** Grid1 */
      grid1: string;
      /** Grid2 */
      grid2: string;
      /** Gridopacity */
      gridOpacity: string;
      /** Gridwidth */
      gridWidth: string;
      /** Opacity */
      opacity: string;
      /** Samples1 */
      samples1: string;
      /** Samples2 */
      samples2: string;
      /** Shaded */
      shaded: string;
      /** Usecalculatedvisibility */
      useCalculatedVisibility: boolean;
      /** Visible */
      visible: boolean;
      /** Zbias */
      zBias: string;
      /** Zindex */
      zIndex: string;
      /** Zorder */
      zOrder: string;
    };
    /** ExplicitSurfaceProperties */
    ExplicitSurfaceProperties: {
      /** Calculatedvisibility */
      calculatedVisibility: string;
      /** Color */
      color: string;
      colorExpr: components["schemas"]["FunctionAssignmentObj"];
      /** Description */
      description: string;
      domain: components["schemas"]["FunctionAssignmentArray"];
      expr: components["schemas"]["FunctionAssignmentObj"];
      /** Grid1 */
      grid1: string;
      /** Grid2 */
      grid2: string;
      /** Gridopacity */
      gridOpacity: string;
      /** Gridwidth */
      gridWidth: string;
      /** Opacity */
      opacity: string;
      /** Samples1 */
      samples1: string;
      /** Samples2 */
      samples2: string;
      /** Shaded */
      shaded: string;
      /** Usecalculatedvisibility */
      useCalculatedVisibility: boolean;
      /** Visible */
      visible: boolean;
      /** Zbias */
      zBias: string;
      /** Zindex */
      zIndex: string;
      /** Zorder */
      zOrder: string;
    };
    /** ExprArray */
    ExprArray: {
      /** Items */
      items: components["schemas"]["ExprObj"][];
      /**
       * Type
       * @constant
       */
      type: "array";
    };
    /** ExprObj */
    ExprObj: {
      /** Expr */
      expr: string;
      /**
       * Type
       * @constant
       */
      type: "expr";
    };
    /** FolderItem */
    FolderItem: {
      /** Id */
      id: string;
      properties: components["schemas"]["FolderProperties"];
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "FOLDER";
    };
    /** FolderProperties */
    FolderProperties: {
      /** Description */
      description: string;
      /** Iscollapsed */
      isCollapsed: string;
    };
    /** FunctionAssignmentArray */
    FunctionAssignmentArray: {
      /** Items */
      items: components["schemas"]["FunctionAssignmentObj"][];
      /**
       * Type
       * @constant
       */
      type: "array";
    };
    /** FunctionAssignmentObj */
    FunctionAssignmentObj: {
      /** Name */
      name: string;
      /** Params */
      params: string[];
      /** Rhs */
      rhs: string;
      /**
       * Type
       * @constant
       */
      type: "function-assignment";
    };
    /** GridItem */
    GridItem: {
      /** Id */
      id: string;
      properties: components["schemas"]["GridProperties"];
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "GRID";
    };
    /** GridProperties */
    GridProperties: {
      /**
       * Axes
       * @enum {string}
       */
      axes: "xy" | "yz" | "zx";
      /** Calculatedvisibility */
      calculatedVisibility: string;
      /** Color */
      color: string;
      /** Description */
      description: string;
      /** Divisions */
      divisions: string;
      /** Opacity */
      opacity: string;
      /** Snap */
      snap: string;
      /** Usecalculatedvisibility */
      useCalculatedVisibility: boolean;
      /** Visible */
      visible: boolean;
      /** Width */
      width: string;
      /** Zbias */
      zBias: string;
      /** Zindex */
      zIndex: string;
      /** Zorder */
      zOrder: string;
    };
    /** ImplicitSurfaceItem */
    ImplicitSurfaceItem: {
      /** Id */
      id: string;
      properties: components["schemas"]["ImplicitSurfaceProperties"];
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "IMPLICIT_SURFACE";
    };
    /** ImplicitSurfaceProperties */
    ImplicitSurfaceProperties: {
      /** Calculatedvisibility */
      calculatedVisibility: string;
      /** Color */
      color: string;
      /** Description */
      description: string;
      domain: components["schemas"]["ExprArray"];
      lhs: components["schemas"]["FunctionAssignmentObj"];
      /** Opacity */
      opacity: string;
      rhs: components["schemas"]["FunctionAssignmentObj"];
      /** Samples */
      samples: string;
      /** Shaded */
      shaded: string;
      /** Usecalculatedvisibility */
      useCalculatedVisibility: boolean;
      /** Visible */
      visible: boolean;
      /** Zbias */
      zBias: string;
      /** Zindex */
      zIndex: string;
      /** Zorder */
      zOrder: string;
    };
    /** Input */
    Input: {
      /**
       * Limit
       * @default 20
       */
      limit?: number;
      /**
       * Offset
       * @default 0
       */
      offset?: number;
    };
    /** LegacySceneInSchema */
    LegacySceneInSchema: {
      /** Dehydrated */
      dehydrated: unknown;
    };
    /** LegacySceneOutSchema */
    LegacySceneOutSchema: {
      /** Dehydrated */
      dehydrated: unknown;
      /** Key */
      key: string;
    };
    /** LineItem */
    LineItem: {
      /** Id */
      id: string;
      properties: components["schemas"]["LineProperties"];
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "LINE";
    };
    /** LineProperties */
    LineProperties: {
      /** Calculatedvisibility */
      calculatedVisibility: string;
      /** Color */
      color: string;
      /** Coords */
      coords: string;
      /** Description */
      description: string;
      /** End */
      end: string;
      /** Label */
      label: string;
      /** Labelvisible */
      labelVisible: string;
      /** Opacity */
      opacity: string;
      /** Size */
      size: string;
      /** Start */
      start: string;
      /** Usecalculatedvisibility */
      useCalculatedVisibility: boolean;
      /** Visible */
      visible: boolean;
      /** Width */
      width: string;
      /** Zbias */
      zBias: string;
      /** Zindex */
      zIndex: string;
      /** Zorder */
      zOrder: string;
    };
    /** MathItem */
    MathItem:
      | components["schemas"]["AxisItem"]
      | components["schemas"]["BooleanVariableItem"]
      | components["schemas"]["CameraItem"]
      | components["schemas"]["ExplicitSurfaceItem"]
      | components["schemas"]["ExplicitSurfacePolarItem"]
      | components["schemas"]["FolderItem"]
      | components["schemas"]["GridItem"]
      | components["schemas"]["ImplicitSurfaceItem"]
      | components["schemas"]["LineItem"]
      | components["schemas"]["ParametricCurveItem"]
      | components["schemas"]["ParametricSurfaceItem"]
      | components["schemas"]["PointItem"]
      | components["schemas"]["VariableItem"]
      | components["schemas"]["VariableSliderItem"]
      | components["schemas"]["VectorItem"]
      | components["schemas"]["VectorFieldItem"];
    /** MiniSceneSchema */
    MiniSceneSchema: {
      /** Archived */
      archived: boolean;
      /** Author */
      author?: number | null;
      /**
       * Createddate
       * Format: date-time
       */
      createdDate: string;
      /** Key */
      key: string;
      /**
       * Modifieddate
       * Format: date-time
       */
      modifiedDate: string;
      /** Title */
      title?: string | null;
    };
    /** PagedMiniSceneSchema */
    PagedMiniSceneSchema: {
      /** Count */
      count: number;
      /** Items */
      items: components["schemas"]["MiniSceneSchema"][];
    };
    /** ParametricCurveItem */
    ParametricCurveItem: {
      /** Id */
      id: string;
      properties: components["schemas"]["ParametricCurveProperties"];
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "PARAMETRIC_CURVE";
    };
    /** ParametricCurveProperties */
    ParametricCurveProperties: {
      /** Calculatedvisibility */
      calculatedVisibility: string;
      /** Color */
      color: string;
      /** Description */
      description: string;
      domain: components["schemas"]["ExprArray"];
      /** End */
      end: string;
      expr: components["schemas"]["FunctionAssignmentObj"];
      /** Opacity */
      opacity: string;
      /** Samples1 */
      samples1: string;
      /** Size */
      size: string;
      /** Start */
      start: string;
      /** Usecalculatedvisibility */
      useCalculatedVisibility: boolean;
      /** Visible */
      visible: boolean;
      /** Width */
      width: string;
      /** Zbias */
      zBias: string;
      /** Zindex */
      zIndex: string;
      /** Zorder */
      zOrder: string;
    };
    /** ParametricSurfaceItem */
    ParametricSurfaceItem: {
      /** Id */
      id: string;
      properties: components["schemas"]["ParametricSurfaceProperties"];
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "PARAMETRIC_SURFACE";
    };
    /** ParametricSurfaceProperties */
    ParametricSurfaceProperties: {
      /** Calculatedvisibility */
      calculatedVisibility: string;
      /** Color */
      color: string;
      colorExpr: components["schemas"]["FunctionAssignmentObj"];
      /** Description */
      description: string;
      domain: components["schemas"]["FunctionAssignmentArray"];
      expr: components["schemas"]["FunctionAssignmentObj"];
      /** Grid1 */
      grid1: string;
      /** Grid2 */
      grid2: string;
      /** Gridopacity */
      gridOpacity: string;
      /** Gridwidth */
      gridWidth: string;
      /** Opacity */
      opacity: string;
      /** Samples1 */
      samples1: string;
      /** Samples2 */
      samples2: string;
      /** Shaded */
      shaded: string;
      /** Usecalculatedvisibility */
      useCalculatedVisibility: boolean;
      /** Visible */
      visible: boolean;
      /** Zbias */
      zBias: string;
      /** Zindex */
      zIndex: string;
      /** Zorder */
      zOrder: string;
    };
    /** PointItem */
    PointItem: {
      /** Id */
      id: string;
      properties: components["schemas"]["PointProperties"];
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "POINT";
    };
    /** PointProperties */
    PointProperties: {
      /** Calculatedvisibility */
      calculatedVisibility: string;
      /** Color */
      color: string;
      /** Coords */
      coords: string;
      /** Description */
      description: string;
      /** Label */
      label: string;
      /** Labelvisible */
      labelVisible: string;
      /** Opacity */
      opacity: string;
      /** Size */
      size: string;
      /** Usecalculatedvisibility */
      useCalculatedVisibility: boolean;
      /** Visible */
      visible: boolean;
      /** Zbias */
      zBias: string;
      /** Zindex */
      zIndex: string;
      /** Zorder */
      zOrder: string;
    };
    /** SceneCreateSchema */
    SceneCreateSchema: {
      /**
       * Archived
       * @default false
       */
      archived?: boolean;
      /** Itemorder */
      itemOrder: {
        [key: string]: string[];
      };
      /** Items */
      items: components["schemas"]["MathItem"][];
      /** Title */
      title?: string | null;
    };
    /** SceneFilterSchema */
    SceneFilterSchema: {
      /** Archived */
      archived?: boolean | null;
      /** Title */
      title?: string | null;
    };
    /** ScenePatchSchema */
    ScenePatchSchema: {
      /** Archived */
      archived?: boolean | null;
      /** Itemorder */
      itemOrder?: {
        [key: string]: string[];
      };
      /** Items */
      items?: components["schemas"]["MathItem"][];
      /** Title */
      title?: string | null;
    };
    /** SceneSchema */
    SceneSchema: {
      /** Archived */
      archived: boolean;
      /** Author */
      author?: number | null;
      /**
       * Createddate
       * Format: date-time
       */
      createdDate: string;
      /** Islegacy */
      isLegacy: boolean;
      /** Itemorder */
      itemOrder: {
        [key: string]: string[];
      };
      /** Items */
      items: components["schemas"]["MathItem"][];
      /** Key */
      key: string;
      /**
       * Modifieddate
       * Format: date-time
       */
      modifiedDate: string;
      /** Title */
      title?: string | null;
    };
    /** StrArray */
    StrArray: {
      /** Items */
      items: string[];
      /**
       * Type
       * @constant
       */
      type: "array";
    };
    /** UserSchema */
    UserSchema: {
      /** Email */
      email: string;
      /** Id */
      id: number;
      /** Public Nickname */
      public_nickname: string;
    };
    /** UserUpdateSchema */
    UserUpdateSchema: {
      /** Public Nickname */
      public_nickname: string;
    };
    /** VariableItem */
    VariableItem: {
      /** Id */
      id: string;
      properties: components["schemas"]["VariableProperties"];
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "VARIABLE";
    };
    /** VariableProperties */
    VariableProperties: {
      /** Description */
      description: string;
      value: components["schemas"]["AssignmentObj"];
    };
    /** VariableSliderItem */
    VariableSliderItem: {
      /** Id */
      id: string;
      properties: components["schemas"]["VariableSliderProperties"];
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "VARIABLE_SLIDER";
    };
    /** VariableSliderProperties */
    VariableSliderProperties: {
      /** Description */
      description: string;
      /** Duration */
      duration: string;
      /** Fps */
      fps: string;
      /** Isanimating */
      isAnimating: string;
      range: components["schemas"]["StrArray"];
      /** Speedmultiplier */
      speedMultiplier: string;
      value: components["schemas"]["AssignmentObj"];
    };
    /** VectorFieldItem */
    VectorFieldItem: {
      /** Id */
      id: string;
      properties: components["schemas"]["VectorFieldProperties"];
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "VECTOR_FIELD";
    };
    /** VectorFieldProperties */
    VectorFieldProperties: {
      /** Calculatedvisibility */
      calculatedVisibility: string;
      /** Color */
      color: string;
      /** Description */
      description: string;
      domain: components["schemas"]["ExprArray"];
      /** End */
      end: string;
      expr: components["schemas"]["FunctionAssignmentObj"];
      /** Opacity */
      opacity: string;
      /** Samples1 */
      samples1: string;
      /** Samples2 */
      samples2: string;
      /** Samples3 */
      samples3: string;
      /** Scale */
      scale: string;
      /** Size */
      size: string;
      /** Start */
      start: string;
      /** Usecalculatedvisibility */
      useCalculatedVisibility: boolean;
      /** Visible */
      visible: boolean;
      /** Width */
      width: string;
      /** Zbias */
      zBias: string;
      /** Zindex */
      zIndex: string;
      /** Zorder */
      zOrder: string;
    };
    /** VectorItem */
    VectorItem: {
      /** Id */
      id: string;
      properties: components["schemas"]["VectorProperties"];
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "VECTOR";
    };
    /** VectorProperties */
    VectorProperties: {
      /** Calculatedvisibility */
      calculatedVisibility: string;
      /** Color */
      color: string;
      /** Components */
      components: string;
      /** Description */
      description: string;
      /** End */
      end: string;
      /** Label */
      label: string;
      /** Labelvisible */
      labelVisible: string;
      /** Opacity */
      opacity: string;
      /** Size */
      size: string;
      /** Start */
      start: string;
      /** Tail */
      tail: string;
      /** Usecalculatedvisibility */
      useCalculatedVisibility: boolean;
      /** Visible */
      visible: boolean;
      /** Width */
      width: string;
      /** Zbias */
      zBias: string;
      /** Zindex */
      zIndex: string;
      /** Zorder */
      zOrder: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  authentication_api_activate: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ActivationSchema"];
      };
    };
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  authentication_api_get_me: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserSchema"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  authentication_api_patch_me: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserUpdateSchema"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserSchema"];
        };
      };
    };
  };
  authentication_api_delete_me: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DeleteAccountSchema"];
      };
    };
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DeleteAccountError"];
        };
      };
    };
  };
  scenes_api_create_legacy: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LegacySceneInSchema"];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LegacySceneOutSchema"];
        };
      };
    };
  };
  scenes_api_get_legacy: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        key: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LegacySceneOutSchema"];
        };
      };
    };
  };
  scenes_api_list_scenes: {
    parameters: {
      query?: {
        title?: string | null;
        archived?: boolean | null;
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PagedMiniSceneSchema"];
        };
      };
    };
  };
  scenes_api_create_scene: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SceneCreateSchema"];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SceneSchema"];
        };
      };
    };
  };
  scenes_api_my_scenes: {
    parameters: {
      query?: {
        title?: string | null;
        archived?: boolean | null;
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PagedMiniSceneSchema"];
        };
      };
    };
  };
  scenes_api_get_scene: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        key: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SceneSchema"];
        };
      };
    };
  };
  scenes_api_delete_scene: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        key: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  scenes_api_update_scene: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        key: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ScenePatchSchema"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SceneSchema"];
        };
      };
    };
  };
}
