# Generated by Django 4.1.6 on 2023-03-08 01:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scenes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Scene",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=80, unique=True)),
                ("items", models.JSONField()),
                ("item_order", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("title", models.TextField()),
            ],
        ),
    ]
