# Generated by Django 4.2.2 on 2023-06-26 00:20

from django.db import migrations, models

import scenes.models


class Migration(migrations.Migration):
    dependencies = [
        ("scenes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scene",
            name="items",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="scene",
            name="key",
            field=models.CharField(
                default=scenes.models._random_key, max_length=80, unique=True
            ),
        ),
    ]
