# Generated by Django 4.1.7 on 2023-03-14 00:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scenes", "0002_scene"),
    ]

    operations = [
        migrations.AddField(
            model_name="legacyscene",
            name="migration_note",
            field=models.TextField(default=""),
        ),
    ]
