# Generated by Django 4.2.7 on 2023-12-31 20:20

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):
    dependencies = [
        ("scenes", "0003_scene_author"),
    ]

    operations = [
        TrigramExtension(),
    ]
