# Generated by Django 4.2.7 on 2023-12-31 20:33

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("scenes", "0004_trigram_extension"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="scene",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["title"],
                name="title_gin_trgm_index",
                opclasses=["gin_trgm_ops"],
            ),
        ),
    ]
