# Generated by Django 4.2.7 on 2024-01-01 21:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("scenes", "0005_scene_title_gin_trgm_index"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="scene",
            options={"ordering": ["id"]},
        ),
    ]
