# Generated by Django 4.2.7 on 2024-01-07 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scenes", "0006_alter_scene_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="scene",
            old_name="created_at",
            new_name="created_date",
        ),
        migrations.AddField(
            model_name="scene",
            name="modified_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
