# Generated by Django 4.2.7 on 2024-01-13 18:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    replaces = [
        ("scenes", "0007_rename_created_at_scene_created_date_and_more"),
        ("scenes", "0008_alter_scene_created_date_alter_scene_modified_date"),
        ("scenes", "0009_alter_scene_created_date_alter_scene_modified_date"),
        ("scenes", "0010_alter_scene_created_date_alter_scene_modified_date"),
    ]

    dependencies = [
        ("scenes", "0006_alter_scene_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="scene",
            old_name="created_at",
            new_name="created_date",
        ),
        migrations.AlterField(
            model_name="scene",
            name="created_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="scene",
            name="modified_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
