# Generated by Django 5.1.4 on 2025-01-18 00:39

import scenes.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scenes", "0008_scene_archived"),
    ]

    operations = [
        migrations.AlterField(
            model_name="legacyscene",
            name="key",
            field=models.CharField(
                default=scenes.models.random_key, max_length=80, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="scene",
            name="key",
            field=models.CharField(
                default=scenes.models.random_key, max_length=80, unique=True
            ),
        ),
    ]
