# Generated by Django 5.1.5 on 2025-01-30 01:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scenes", "0009_alter_legacyscene_key_alter_scene_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="scene",
            name="times_accessed",
            field=models.IntegerField(default=0),
        ),
    ]
