# Generated by Django 5.1.5 on 2025-02-23 21:12

from django.db import migrations
from django.core.paginator import Paginator


def set_item_visibility(item):
    props = item.get("properties", {})
    if "visible" in props:
        visible = props["visible"]
        if visible == "true":
            props["visible"] = True
            props["calculatedVisibility"] = ""
            props["useCalculatedVisibility"] = False
        elif visible == "false":
            props["visible"] = False
            props["calculatedVisibility"] = ""
            props["useCalculatedVisibility"] = False
        else:
            props["calculatedVisibility"] = visible
            props["useCalculatedVisibility"] = True
            props["visible"] = True


def unset_item_visibility(item):
    props = item.get("properties", {})
    if "visible" in props:
        calculated_visibility = props.get("calculatedVisibility", "")
        visible = props["visible"]
        if calculated_visibility:
            props["visible"] = calculated_visibility
        elif visible:
            props["visible"] = "true"
        else:
            props["visible"] = "false"
    del props["calculatedVisibility"]
    del props["useCalculatedVisibility"]


def set_calculated_visibility(apps, schema_editor):
    Scene = apps.get_model("scenes", "Scene")
    pages = Paginator(Scene.objects.all(), 100)
    for page in pages:
        for scene in page:
            items = scene.items
            for item in items:
                set_item_visibility(item)
            scene.save()


def unset_calculated_visibility(apps, schema_editor):
    Scene = apps.get_model("scenes", "Scene")
    pages = Paginator(Scene.objects.all(), 100)
    for page in pages:
        for scene in page:
            items = scene.items
            for item in items:
                unset_item_visibility(item)
            scene.save()


class Migration(migrations.Migration):
    dependencies = [
        ("scenes", "0010_scene_times_accessed"),
    ]

    operations = [
        migrations.RunPython(set_calculated_visibility, unset_calculated_visibility),
    ]
