# Generated by Django 5.2 on 2025-05-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scenes", "0012_alter_scene_items"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scene",
            name="items",
            field=models.JSONField(),
        ),
    ]
