# Generated by Django 5.2 on 2025-08-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scenes", "0014_set_z_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="scene",
            name="is_legacy",
            field=models.BooleanField(default=False),
        ),
    ]
