# Generated by Django 5.2.12 on 2026-06-30 11:59

import django.core.validators
import scenes.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scenes", "0016_alter_scene_items"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="scene",
            name="key",
            field=models.CharField(
                default=scenes.models.random_key,
                max_length=80,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Scene key must be at least 2 characters and not a reserved word.",
                        regex="^(?!app$).{2,}$",
                    )
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="scene",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("key__length__gte", 2), models.Q(("key", "app"), _negated=True)
                ),
                name="scene_key_not_reserved",
            ),
        ),
    ]
