# Generated by Django 6.0.7 on 2026-08-17 20:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scenes", "0017_scene_key_reserved"),
    ]

    operations = [
        migrations.CreateModel(
            name="RenderDay",
            fields=[
                ("day", models.DateField(primary_key=True, serialize=False)),
                ("count", models.PositiveIntegerField(default=0)),
                ("modified", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="RenderMonth",
            fields=[
                ("month", models.DateField(primary_key=True, serialize=False)),
                ("count", models.PositiveIntegerField(default=0)),
                ("modified", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
