# Generated by Django 6.0.7 on 2026-10-02 02:26

import django.utils.timezone
from django.db import migrations, models
from django.db.models import F


def backfill(apps, schema_editor):
    # The last content edit is unknown; modified_date is no earlier than it, so
    # no existing render can look newer than its scene's content.
    Scene = apps.get_model("scenes", "Scene")
    Scene.objects.update(content_modified_date=F("modified_date"))


class Migration(migrations.Migration):
    dependencies = [
        ("scenes", "0019_alter_scene_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="scene",
            name="content_modified_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
