# Generated by Django 6.0.7 on 2026-10-02 02:32

import django.db.models.functions.datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scenes", "0019_alter_scene_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="scene",
            name="content_modified_date",
            field=models.DateTimeField(
                db_default=django.db.models.functions.datetime.Now(),
                default=django.utils.timezone.now,
            ),
        ),
    ]
