# Generated by Django 6.0.7 on 2026-09-29 00:37

from django.conf import settings
from django.db import migrations, models
from django.db.models import F, Func, Value
from django.db.models.functions import Trim


def normalize_titles(apps, schema_editor):
    """Replace line breaks with spaces, then store "Untitled" as blank."""
    Scene = apps.get_model("scenes", "Scene")
    Scene.objects.filter(title__regex=r"[\r\n]").update(
        title=Trim(
            Func(
                F("title"),
                Value(r"\r\n|[\r\n]"),
                Value(" "),
                Value("g"),
                function="regexp_replace",
            )
        )
    )
    Scene.objects.filter(title="Untitled").update(title="")


class Migration(migrations.Migration):
    dependencies = [
        ("scenes", "0021_backfill_content_modified_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="scene",
            name="title",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.RunPython(normalize_titles, migrations.RunPython.noop),
    ]
