components:
  responses:
    Unauthenticated:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AuthenticationResponse'
      description: 'There is no authenticated session.

        '
  schemas:
    AuthenticationMeta:
      allOf:
      - $ref: '#/components/schemas/BaseAuthenticationMeta'
      - description: 'Metadata available in an authentication related response.

          '
        properties:
          is_authenticated:
            type: boolean
        required:
        - is_authenticated
        type: object
    AuthenticationResponse:
      description: 'An authentication related response.

        '
      properties:
        data:
          properties:
            flows:
              items:
                $ref: '#/components/schemas/Flow'
              type: array
          required:
          - flows
          type: object
        meta:
          $ref: '#/components/schemas/AuthenticationMeta'
        status:
          enum:
          - 401
          type: integer
      required:
      - status
      - data
      - meta
      type: object
    AuthenticatorType:
      description: 'The type of authenticator.

        '
      enum:
      - recovery_codes
      - totp
      - webauthn
      type: string
    BaseAuthenticationMeta:
      properties:
        access_token:
          description: 'The access token (`app` clients only).

            '
          type: string
        session_token:
          description: 'The session token (`app` clients only).

            '
          type: string
      type: object
    Flow:
      properties:
        id:
          enum:
          - login
          - login_by_code
          - mfa_authenticate
          - mfa_reauthenticate
          - provider_redirect
          - provider_signup
          - provider_token
          - reauthenticate
          - signup
          - verify_email
          - verify_phone
          type: string
        is_pending:
          enum:
          - true
          type: boolean
        provider:
          $ref: '#/components/schemas/Provider'
        types:
          description: Matches `settings.MFA_SUPPORTED_TYPES`.
          items:
            $ref: '#/components/schemas/AuthenticatorType'
          type: array
      required:
      - id
      type: object
    Provider:
      properties:
        client_id:
          description: 'The client ID (in case of OAuth2 or OpenID Connect based providers)

            '
          type: string
        flows:
          description: 'The authentication flows the provider integration supports.

            '
          items:
            enum:
            - provider_redirect
            - provider_token
            type: string
          type: array
        id:
          description: 'The provider ID.

            '
          type: string
        name:
          description: 'The name of the provider.

            '
          type: string
        openid_configuration_url:
          description: 'The OIDC discovery or well-known URL (in case of OAuth2 or OpenID Connect based providers)

            '
          type: string
      required:
      - id
      - name
      - flows
      type: object
info:
  description: Trimmed django-allauth headless browser API. Vendored via `manage.py dump_openapi_allauth`.
  title: 'django-allauth: Headless API'
  version: '1'
openapi: 3.0.3
paths:
  /_allauth/browser/v1/auth/session:
    delete:
      description: 'Logs out the user from the current session.

        '
      operationId: logout
      responses:
        '401':
          $ref: '#/components/responses/Unauthenticated'
      summary: Logout
      tags:
      - allauth
