#!/usr/bin/env bash
# Set up a git worktree for local dev and e2e tests.
#
# Writes a .env giving this checkout its own frontend port (3002-3009: the
# main checkout's dev server owns 3000 and the legacy app dev server owns
# 3001) and pointing the e2e email inbox at the main checkout, whose
# webserver/ directory the shared docker backend mounts. The backend is NOT
# duplicated: worktrees talk to the docker stack started from the main
# checkout, which already trusts the worktree ports (see WORKTREE_PORTS in
# webserver/main/origins.py).
set -euo pipefail
cd "$(cd "$(dirname "$0")/.." && pwd)"

# In the main checkout git-dir and git-common-dir coincide (.git); in a
# worktree the git-dir is .git/worktrees/<name> under the main checkout.
git_dir="$(git rev-parse --path-format=absolute --git-dir)"
common_dir="$(git rev-parse --path-format=absolute --git-common-dir)"
main_root="$(dirname "$common_dir")"

if [ "$git_dir" = "$common_dir" ]; then
	echo "This is the main checkout; it uses port 3000 and needs no generated .env." >&2
	echo "Run this script from a git worktree." >&2
	exit 1
fi

if [ -f .env ]; then
	echo ".env already exists in $(pwd); not overwriting." >&2
	exit 1
fi

# Ports claimed by sibling checkouts' .env files.
worktree_paths="$(git worktree list --porcelain | sed -n 's/^worktree //p')"
claimed=" "
while read -r wt; do
	if [ -f "$wt/.env" ]; then
		# A .env with no port lines (e.g. the main checkout's) claims nothing.
		claimed+="$(grep -Eho 'math3d\.localdev:[0-9]+' "$wt/.env" | grep -Eo '[0-9]+$' | sort -u | tr '\n' ' ' || true)"
	fi
done <<<"$worktree_paths"

# Busy if anything answers on the IPv4 or IPv6 loopback (dev servers commonly
# bind only ::1).
port_in_use() {
	(exec 3<>"/dev/tcp/127.0.0.1/$1") 2>/dev/null ||
		(exec 3<>"/dev/tcp/::1/$1") 2>/dev/null
}

port=""
# Keep this range in sync with WORKTREE_PORTS in webserver/main/origins.py.
for p in 3002 3003 3004 3005 3006 3007 3008 3009; do
	case "$claimed" in *" $p "*) continue ;; esac
	if ! port_in_use "$p"; then
		port=$p
		break
	fi
done

if [ -z "$port" ]; then
	echo "No free port found in 3002-3009." >&2
	exit 1
fi

cat >.env <<EOF
# Generated by scripts/setup_worktree_env.sh — per-worktree overrides.
# The docker backend + database are shared with the main checkout
# ($main_root); do not run 'docker compose up' from this worktree.
APP_BASE_URL="http://math3d.localdev:$port"
TEST_APP_URL="http://math3d.localdev:$port"
VITE_DISPLAY_AUTH_FLOWS=true
EMAIL_DIR="$main_root/webserver/private/email"
EOF

# .envrc is untracked in the main checkout, so worktrees don't inherit it.
if [ ! -f .envrc ]; then
	printf 'dotenv_if_exists .env.development\ndotenv_if_exists .env\n' >.envrc
fi
if command -v direnv >/dev/null 2>&1; then
	direnv allow .
fi

echo "Wrote .env: frontend port $port, backend shared with $main_root"
echo "Next steps (if not done): yarn install, then 'just e2e' to run e2e tests."
