"""
Request-level tests for ScopedCorsCredentialsMiddleware: origins in
CORS_ALLOWED_ORIGINS but not in CREDENTIALED_CORS_ORIGINS get anonymous CORS
only — no Access-Control-Allow-Credentials header (issue #1184).
"""

from django.test import Client, override_settings

SPA_ORIGIN = "https://app.example.org"
ANON_ORIGIN = "https://legacy.example.org"

scoped_cors_settings = override_settings(
    CORS_ALLOWED_ORIGINS=[SPA_ORIGIN, ANON_ORIGIN],
    CREDENTIALED_CORS_ORIGINS=[SPA_ORIGIN],
)


@scoped_cors_settings
def test_credentialed_origin_keeps_credentials_header():
    response = Client().get("/health", HTTP_ORIGIN=SPA_ORIGIN)
    assert response.headers["Access-Control-Allow-Origin"] == SPA_ORIGIN
    assert response.headers["Access-Control-Allow-Credentials"] == "true"


@scoped_cors_settings
def test_anonymous_cors_origin_gets_no_credentials_header():
    """The origin stays CORS-allowed; only the credentials grant is withheld."""
    response = Client().get("/health", HTTP_ORIGIN=ANON_ORIGIN)
    assert response.headers["Access-Control-Allow-Origin"] == ANON_ORIGIN
    assert "Access-Control-Allow-Credentials" not in response.headers


@scoped_cors_settings
def test_preflight_from_anonymous_origin_gets_no_credentials_header():
    """
    Preflight responses are generated by CorsMiddleware's request phase (the
    view never runs); the strip must apply to them too, so browsers fail
    credentialed preflights from anonymous-only origins.
    """
    response = Client().options(
        "/health",
        HTTP_ORIGIN=ANON_ORIGIN,
        HTTP_ACCESS_CONTROL_REQUEST_METHOD="GET",
    )
    assert response.headers["Access-Control-Allow-Origin"] == ANON_ORIGIN
    assert "Access-Control-Allow-Credentials" not in response.headers
