"""
Django settings for main project.

Generated by 'django-admin startproject' using Django 4.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import logging

from django.core.exceptions import ImproperlyConfigured

import dj_database_url
import sentry_sdk
from pydantic import ValidationError

from main.env import EnvConfig
from main.origins import (
    cors_allowed_origins,
    credentialed_cors_origins,
    csrf_trusted_origins,
    dev_cors_allowed_origins,
)


logger = logging.getLogger(__name__)

# Every env var this module reads, with types, defaults, and the cross-variable
# boot guards (see main/env.py). Validation errors become the Django-idiomatic
# ImproperlyConfigured so a misconfigured deploy still fails loudly at import.
try:
    ENV = EnvConfig()
except ValidationError as exc:
    raise ImproperlyConfigured(str(exc)) from exc

# Unset DSN ⇒ no-op (dev, CI, tests). EnvConfig already validated the DSN
# above, so a malformed value fails as ImproperlyConfigured, not BadDsn here.
if ENV.SENTRY_DSN:
    sentry_sdk.init(
        dsn=ENV.SENTRY_DSN,
        environment="production",
        release=ENV.APP_VERSION,
        send_default_pii=False,
        traces_sample_rate=ENV.SENTRY_TRACES_SAMPLE_RATE,
    )

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ENV.SECRET_KEY

# Application version
APP_VERSION = ENV.APP_VERSION

# Deployment environment: an explicit dev opt-out (not an inference from the
# hosting platform) that defaults to False, so an unconfigured deploy comes up
# hardened or fails loudly (EnvConfig guards) — never silently with dev-grade
# security. Production-like deploys (prod, rc) leave it unset.
IS_DEVELOPMENT = ENV.IS_DEVELOPMENT

# The SPA origin, e.g. https://next.math3d.org — validated and normalized to a
# bare origin by EnvConfig.
APP_BASE_URL = ENV.APP_BASE_URL

# Screenshot render Worker (packages/screenshots). Bare origin; unset ⇒ the
# render-on-save feature is dark (saves behave as before). See ADR-0002.
SCREENSHOTS_ORIGIN = ENV.SCREENSHOTS_ORIGIN
RENDER_SECRET = ENV.RENDER_SECRET  # noqa: S105 (name, not a secret literal) pragma: allowlist secret

# Per-period reservation caps (ADR-0002 cost protection). Plain constants: they
# rarely change and aren't secret. Monthly ceiling bounds spend to ≤ $10;
# daily is an anti-burst sub-cap.
RENDER_MONTHLY_CAP = 1500
RENDER_DAILY_CAP = 150

DEBUG = False

# Secure cookie defaults — only relaxed for local dev (no TLS).
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

ALLOWED_HOSTS: list[str]
if not IS_DEVELOPMENT:
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    # Set ALLOWED_HOSTS for production
    ALLOWED_HOSTS = ENV.ALLOWED_HOSTS if ENV.ALLOWED_HOSTS else ["api.math3d.org"]
else:
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    ALLOWED_HOSTS = (
        ENV.ALLOWED_HOSTS
        if ENV.ALLOWED_HOSTS
        else ["localhost", "127.0.0.1", "api.math3d.localdev"]
    )

SITE_NAME = "Math3d"

# Logging configuration
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose" if not DEBUG else "simple",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": ENV.LOG_LEVEL,
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": ENV.DJANGO_LOG_LEVEL,
            "propagate": False,
        },
        "authentication": {
            "handlers": ["console"],
            "level": ENV.LOG_LEVEL,
            "propagate": False,
        },
        "scenes": {
            "handlers": ["console"],
            "level": ENV.LOG_LEVEL,
            "propagate": False,
        },
        "main": {
            "handlers": ["console"],
            "level": ENV.LOG_LEVEL,
            "propagate": False,
        },
    },
}

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",  # Required by allauth
    # Django 6.0 requires this app be installed to use GinIndex (see scenes.Scene).
    "django.contrib.postgres",
    "authentication",  # custom app
    "allauth",
    "allauth.account",
    "allauth.headless",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "corsheaders",
    ## Custom apps
    "main",
    "scenes",
]

# The dummy provider mints a session from an unsigned JSON payload, so it must
# never reach a deployed environment; IS_DEVELOPMENT is the whole guard.
if IS_DEVELOPMENT:
    INSTALLED_APPS.append("allauth.socialaccount.providers.dummy")

SITE_ID = 1

# Ninja's default page size is 100; match v0's effective default of 20.
NINJA_PAGINATION_PER_PAGE = 20

MIDDLEWARE = [
    # Must precede CorsMiddleware; see the class docstring.
    "main.middleware.ScopedCorsCredentialsMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# Dropping the middleware is Django's only off switch for CSRF. It exists for
# one manual test: Google sign-in on bare `localhost`, where a single-label
# host cannot carry the domain cookie the SPA reads. See ADR-0005.
if ENV.DISABLE_CSRF:
    if not IS_DEVELOPMENT:
        raise ImproperlyConfigured(
            "DISABLE_CSRF must not be enabled outside development."
        )
    # .remove() raises if the middleware is renamed; a filtered rebuild would
    # silently become a no-op.
    MIDDLEWARE.remove("django.middleware.csrf.CsrfViewMiddleware")

# Explicitly configured origins (Heroku config vars, or a local .env — e.g. the
# legacy math3d-react frontend) are unioned with the dev-only origins
# (APP_BASE_URL plus the worktree frontend ports). In production the dev list is
# empty, so CORS_ALLOWED_ORIGINS is exactly what's configured.
CORS_ALLOWED_ORIGINS = cors_allowed_origins(
    configured=ENV.CORS_ALLOWED_ORIGINS,
    dev=dev_cors_allowed_origins(
        is_development=IS_DEVELOPMENT,
        app_base_url=APP_BASE_URL,
    ),
)
CORS_ALLOW_CREDENTIALS = True
# Prod trusts only APP_BASE_URL; local dev also trusts the CORS origins
# (worktree frontend ports). See the function's docstring.
CSRF_TRUSTED_ORIGINS = csrf_trusted_origins(
    is_development=IS_DEVELOPMENT,
    app_base_url=APP_BASE_URL,
    cors_allowed_origins=CORS_ALLOWED_ORIGINS,
)
# Origins allowed credentialed CORS: ScopedCorsCredentialsMiddleware strips
# Access-Control-Allow-Credentials for origins outside this list, so other
# CORS origins (e.g. the legacy frontend) get anonymous CORS only. A distinct
# grant from CSRF write trust, though the two policies currently coincide.
CREDENTIALED_CORS_ORIGINS = credentialed_cors_origins(
    is_development=IS_DEVELOPMENT,
    app_base_url=APP_BASE_URL,
    cors_allowed_origins=CORS_ALLOWED_ORIGINS,
)

# Cookie auth requires the SPA (next.math3d.org) and API (api.next.math3d.org)
# to share a registrable domain: default SameSite=Lax sends the session cookie,
# and CSRF_COOKIE_DOMAIN (.math3d.org) lets the SPA read the CSRF token.
# EnvConfig enforces that the domain covers the SPA host.
if ENV.CSRF_COOKIE_DOMAIN:
    CSRF_COOKIE_DOMAIN = ENV.CSRF_COOKIE_DOMAIN


AUTHENTICATION_BACKENDS = [
    "allauth.account.auth_backends.AuthenticationBackend",
]

ROOT_URLCONF = "main.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "main.wsgi.application"

##################################################
# allauth settings
##################################################
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_LOGIN_METHODS = {"email"}
# Social-only: allauth unregisters every password URL (login, signup, password
# reset, email verification, password change) and refuses to boot unless email
# verification is off — the provider already asserts a verified address.
SOCIALACCOUNT_ONLY = True
ACCOUNT_EMAIL_VERIFICATION = "none"
# Trimming below ["email*"] would flip the derived SOCIALACCOUNT_QUERY_EMAIL
# false and drop the `email` scope from the provider request.
ACCOUNT_SIGNUP_FIELDS = ["email*"]
ACCOUNT_EMAIL_NOTIFICATIONS = False
ACCOUNT_LOGIN_BY_CODE_ENABLED = False
# Allow revealing whether an email is registered. Acceptable tradeoff for a
# math visualization tool: usability > preventing enumeration.
ACCOUNT_PREVENT_ENUMERATION = False
ACCOUNT_ADAPTER = "authentication.adapter.CustomAccountAdapter"

# No secret: the popup flow verifies Google ID tokens against Google's certs
# with `aud == client_id` and never exchanges an authorization code.
SOCIALACCOUNT_PROVIDERS = {
    "google": {"APP": {"client_id": ENV.GOOGLE_CLIENT_ID, "secret": ""}},
}
# Never adopt an existing account just because a provider asserts its email
# address. Both spellings matter — see main/settings_test.py.
SOCIALACCOUNT_EMAIL_AUTHENTICATION = False
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = False

if ENV.DISABLE_ALLAUTH_RATE_LIMITS:
    if not IS_DEVELOPMENT:
        raise ImproperlyConfigured(
            "DISABLE_ALLAUTH_RATE_LIMITS must not be enabled outside development."
        )
    ACCOUNT_RATE_LIMITS = False

# allauth headless configuration
HEADLESS_ONLY = True
HEADLESS_CLIENTS = ["browser"]
HEADLESS_SERVE_SPECIFICATION = True
# Serve the headless spec via Swagger UI (ships with allauth) to match the v1
# API's /v1/docs; the default is Redoc (headless/spec/redoc_cdn.html).
HEADLESS_SPECIFICATION_TEMPLATE_NAME = "headless/spec/swagger_cdn.html"

##################################################
# End auth settings
##################################################

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

# Empty config ⇒ Django's dummy backend: DB-free commands (makemigrations,
# dump_openapi_*) still run, queries fail loudly. Required in production.
DATABASES = {
    "default": dj_database_url.parse(ENV.DATABASE_URL) if ENV.DATABASE_URL else {}
}


AUTH_USER_MODEL = "authentication.CustomUser"

MAILJET_API_KEY = ENV.MAILJET_API_KEY
MAILJET_SECRET_KEY = ENV.MAILJET_SECRET_KEY

ANYMAIL = {
    "MAILJET_API_KEY": ENV.MAILJET_API_KEY,
    "MAILJET_SECRET_KEY": ENV.MAILJET_SECRET_KEY,
}
if MAILJET_API_KEY and MAILJET_SECRET_KEY:
    EMAIL_BACKEND = "anymail.backends.mailjet.EmailBackend"
else:
    logger.warning(
        "MAILJET_API_KEY and MAILJET_SECRET_KEY settings not found. Using email console backend."
    )
    EMAIL_BACKEND = "django.core.mail.backends.filebased.EmailBackend"
    EMAIL_FILE_PATH = "./private/email/"

DEFAULT_FROM_EMAIL = ENV.DEFAULT_FROM_EMAIL
SERVER_EMAIL = ENV.SERVER_EMAIL

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

### Static files (CSS, JavaScript, Images)
STATIC_ROOT = BASE_DIR / "staticfiles"
STATIC_URL = "static/"

# WhiteNoise configuration for static files
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

INGESTION_DATABASE_URL = ENV.INGESTION_DATABASE_URL

# Feature flags
ENABLE_REGISTRATION = ENV.ENABLE_REGISTRATION
