"""
Django settings for main project.

Generated by 'django-admin startproject' using Django 4.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import urlparse
import logging

from django.core.exceptions import ImproperlyConfigured

import dj_database_url
import environ

from main.origins import (
    cors_allowed_origins,
    csrf_trusted_origins,
    dev_cors_allowed_origins,
)


logger = logging.getLogger(__name__)

env = environ.Env(
    CORS_ALLOWED_ORIGINS=(list, []),
    SECRET_KEY=(str, ""),
    MAILJET_API_KEY=(str, ""),
    MAILJET_SECRET_KEY=(str, ""),
    DEFAULT_FROM_EMAIL=(str, ""),
    SERVER_EMAIL=(str, ""),
    APP_BASE_URL=(str, ""),
    INGESTION_DATABASE_URL=(str, ""),
    ALLOWED_HOSTS=(list, []),
    # Deployment environment. IS_PRODUCTION drives all production hardening;
    # IS_HEROKU is its deprecated predecessor, read only to fail loudly if a
    # deployment still relies on it.
    IS_PRODUCTION=(bool, False),
    IS_HEROKU=(bool, False),
    # Logging
    LOG_LEVEL=(str, "INFO"),
    DJANGO_LOG_LEVEL=(str, "INFO"),
    # Version
    APP_VERSION=(str, "unknown"),
    # Feature flags
    ENABLE_REGISTRATION=(bool, False),
    CSRF_COOKIE_DOMAIN=(str, ""),
    DISABLE_ALLAUTH_RATE_LIMITS=(bool, False),
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# Application version
APP_VERSION = env("APP_VERSION")

# Deployment environment: an explicit flag, not an inference from the hosting
# platform, so a deploy that forgets it fails loudly below instead of silently
# starting with dev-grade security.
IS_PRODUCTION = env("IS_PRODUCTION")
if env("IS_HEROKU") and not IS_PRODUCTION:
    raise ImproperlyConfigured(
        "IS_HEROKU is deprecated and no longer drives production hardening. "
        "Set IS_PRODUCTION=True on this deployment (and remove IS_HEROKU)."
    )

# The SPA origin, e.g. https://next.math3d.org. Normalized (no trailing slash)
# because paths are appended to it below (HEADLESS_FRONTEND_URLS) and it is
# used verbatim as an origin (CORS/CSRF trust).
APP_BASE_URL = env("APP_BASE_URL").rstrip("/")

DEBUG = False

# Secure cookie defaults — only relaxed for local dev (no TLS).
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

ALLOWED_HOSTS: list[str]
if IS_PRODUCTION:
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    if not APP_BASE_URL:
        raise ImproperlyConfigured(
            "APP_BASE_URL is required in production (used for CSRF_TRUSTED_ORIGINS and email links)."
        )
    if not env("CSRF_COOKIE_DOMAIN"):
        raise ImproperlyConfigured(
            "CSRF_COOKIE_DOMAIN is required in production; without it the SPA "
            "cannot read the CSRF token and all authenticated writes fail."
        )
    # Set ALLOWED_HOSTS for production
    ALLOWED_HOSTS = env("ALLOWED_HOSTS") if env("ALLOWED_HOSTS") else ["api.math3d.org"]
else:
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    ALLOWED_HOSTS = (
        env("ALLOWED_HOSTS")
        if env("ALLOWED_HOSTS")
        else ["localhost", "127.0.0.1", "api.math3d.localdev"]
    )

SITE_NAME = "Math3d"

# Logging configuration
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose" if not DEBUG else "simple",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": env("LOG_LEVEL"),
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": env("DJANGO_LOG_LEVEL"),
            "propagate": False,
        },
        "authentication": {
            "handlers": ["console"],
            "level": env("LOG_LEVEL"),
            "propagate": False,
        },
        "scenes": {
            "handlers": ["console"],
            "level": env("LOG_LEVEL"),
            "propagate": False,
        },
        "main": {
            "handlers": ["console"],
            "level": env("LOG_LEVEL"),
            "propagate": False,
        },
    },
}

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",  # Required by allauth
    "authentication",  # custom app
    "allauth",
    "allauth.account",
    "allauth.headless",
    "corsheaders",
    ## Custom apps
    "main",
    "scenes",
]

SITE_ID = 1

# Ninja's default page size is 100; match v0's effective default of 20.
NINJA_PAGINATION_PER_PAGE = 20

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# Explicitly configured origins (Heroku config vars, or a local .env — e.g. the
# legacy math3d-react frontend) are unioned with the dev-only origins
# (APP_BASE_URL plus the worktree frontend ports). In production the dev list is
# empty, so CORS_ALLOWED_ORIGINS is exactly what's configured.
CORS_ALLOWED_ORIGINS = cors_allowed_origins(
    configured=env("CORS_ALLOWED_ORIGINS"),
    dev=dev_cors_allowed_origins(
        is_production=IS_PRODUCTION,
        app_base_url=APP_BASE_URL,
    ),
)
CORS_ALLOW_CREDENTIALS = True
# Prod trusts only APP_BASE_URL; local dev also trusts the CORS origins
# (worktree frontend ports). See the function's docstring.
CSRF_TRUSTED_ORIGINS = csrf_trusted_origins(
    is_production=IS_PRODUCTION,
    app_base_url=APP_BASE_URL,
    cors_allowed_origins=CORS_ALLOWED_ORIGINS,
)

# Cookie auth requires the SPA (next.math3d.org) and API (api.next.math3d.org)
# to share a registrable domain: default SameSite=Lax sends the session cookie,
# and CSRF_COOKIE_DOMAIN (.math3d.org) lets the SPA read the CSRF token. The
# check below makes the shared-domain constraint explicit for the CSRF half.
_csrf_cookie_domain = env("CSRF_COOKIE_DOMAIN")
if _csrf_cookie_domain:
    CSRF_COOKIE_DOMAIN = _csrf_cookie_domain
    _registrable_domain = _csrf_cookie_domain.lstrip(".")
    _spa_host = urlparse(APP_BASE_URL).hostname or ""
    if APP_BASE_URL and not (
        _spa_host == _registrable_domain
        or _spa_host.endswith("." + _registrable_domain)
    ):
        raise ImproperlyConfigured(
            f"CSRF_COOKIE_DOMAIN {_csrf_cookie_domain!r} does not cover the SPA "
            f"host {_spa_host!r} (from APP_BASE_URL), so the SPA could not read "
            "the CSRF token."
        )


AUTHENTICATION_BACKENDS = [
    "allauth.account.auth_backends.AuthenticationBackend",
]

ROOT_URLCONF = "main.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "main.wsgi.application"

##################################################
# allauth settings
##################################################
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_LOGIN_METHODS = {"email"}
# No password2: headless mode doesn't use it (password confirmation is
# handled client-side). See https://docs.allauth.org/en/latest/headless/faq.html
ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*"]
ACCOUNT_EMAIL_VERIFICATION = "mandatory"
ACCOUNT_LOGIN_BY_CODE_ENABLED = False
# Allow revealing whether an email is registered. Acceptable tradeoff for a
# math visualization tool: usability > preventing enumeration.
ACCOUNT_PREVENT_ENUMERATION = False
ACCOUNT_ADAPTER = "authentication.adapter.CustomAccountAdapter"
# ACCOUNT_SIGNUP_FORM_CLASS (not ACCOUNT_FORMS) is the correct setting for
# injecting extra fields alongside allauth's built-in signup form.
ACCOUNT_SIGNUP_FORM_CLASS = "authentication.forms.CustomSignupForm"

if env("DISABLE_ALLAUTH_RATE_LIMITS"):
    if SESSION_COOKIE_SECURE:
        raise ImproperlyConfigured(
            "DISABLE_ALLAUTH_RATE_LIMITS must not be enabled on a secure-cookie "
            "(TLS/production) deployment."
        )
    ACCOUNT_RATE_LIMITS = False

# allauth headless configuration
HEADLESS_ONLY = True
HEADLESS_ADAPTER = "authentication.adapter.CustomHeadlessAdapter"
HEADLESS_CLIENTS = ["browser"]
HEADLESS_SERVE_SPECIFICATION = True
# Serve the headless spec via Swagger UI (ships with allauth) to match the v1
# API's /v1/docs; the default is Redoc (headless/spec/redoc_cdn.html).
HEADLESS_SPECIFICATION_TEMPLATE_NAME = "headless/spec/swagger_cdn.html"
HEADLESS_FRONTEND_URLS = {
    "account_confirm_email": f"{APP_BASE_URL}/?overlay=activate&key={{key}}",
    "account_reset_password_from_key": f"{APP_BASE_URL}/?overlay=reset-confirm&key={{key}}",
}

##################################################
# End auth settings
##################################################

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.config(
        default=os.environ.get(
            "DATABASE_URL",
            f"sqlite:///{os.path.join(BASE_DIR, 'db.sqlite3')}",
        )
    )
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {
            "min_length": 9,
        },
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

AUTH_USER_MODEL = "authentication.CustomUser"

MAILJET_API_KEY = env("MAILJET_API_KEY")
MAILJET_SECRET_KEY = env("MAILJET_SECRET_KEY")

ANYMAIL = {
    "MAILJET_API_KEY": env("MAILJET_API_KEY"),
    "MAILJET_SECRET_KEY": env("MAILJET_SECRET_KEY"),
}
if MAILJET_API_KEY and MAILJET_SECRET_KEY:
    EMAIL_BACKEND = "anymail.backends.mailjet.EmailBackend"
else:
    logger.warning(
        "MAILJET_API_KEY and MAILJET_SECRET_KEY settings not found. Using email console backend."
    )
    EMAIL_BACKEND = "django.core.mail.backends.filebased.EmailBackend"
    EMAIL_FILE_PATH = "./private/email/"

DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL")
SERVER_EMAIL = env("SERVER_EMAIL")

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

### Static files (CSS, JavaScript, Images)
STATIC_ROOT = BASE_DIR / "staticfiles"
STATIC_URL = "static/"

# WhiteNoise configuration for static files
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

INGESTION_DATABASE_URL = env("INGESTION_DATABASE_URL")

# Feature flags
ENABLE_REGISTRATION = env("ENABLE_REGISTRATION")
