export const inlineShortcuts = {
  // trig
  sin: "\\sin(#?)",
  cos: "\\cos(#?)",
  tan: "\\tan(#?)",
  csc: "\\csc(#?)",
  sec: "\\sec(#?)",
  cot: "\\cot(#?)",
  // inverse trig
  arcsin: "\\arcsin(#?)",
  arccos: "\\arccos(#?)",
  arctan: "\\arctan(#?)",
  arccsc: "\\arccsc(#?)",
  arcsec: "\\arcsec(#?)",
  arccot: "\\arccot(#?)",
  // hyperbolic trig
  sinh: "\\sinh(#?)",
  cosh: "\\cosh(#?)",
  tanh: "\\tanh(#?)",
  csch: "\\csch(#?)",
  sech: "\\sech(#?)",
  coth: "\\coth(#?)",
  // inverse hyperbolic trig
  arcsinh: "\\operatorname{arcsinh}(#?)",
  arccosh: "\\operatorname{arccosh}(#?)",
  arctanh: "\\operatorname{arctanh}(#?)",
  arccsch: "\\operatorname{arccsch}(#?)",
  arcsech: "\\operatorname{arcsech}(#?)",
  arccoth: "\\operatorname{arccoth}(#?)",
  // misc
  abs: "\\abs",
  sign: "\\operatorname{sign}(#?)",
  floor: "\\operatorname{floor}(#?)",
  ceil: "\\operatorname{ceil}(#?)",
  // sqrt
  sqrt: "\\sqrt{#?}",
  // exp
  exp: "\\exp",
  ln: "\\ln",
  log: "\\log",
  // greek
  alpha: "\\alpha",
  beta: "\\beta",
  gamma: "\\gamma",
  delta: "\\delta",
  epsilon: "\\epsilon",
  zeta: "\\zeta",
  eta: "\\eta",
  theta: "\\theta",
  iota: "\\iota",
  kappa: "\\kappa",
  lambda: "\\lambda",
  mu: "\\mu",
  nu: "\\nu",
  xi: "\\xi",
  omicron: "\\omicron",
  pi: "\\pi",
  rho: "\\rho",
  sigma: "\\sigma",
  tau: "\\tau",
  upsilon: "\\upsilon",
  phi: "\\phi",
  chi: "\\chi",
  psi: "\\psi",
  omega: "\\omega",
  // green, Capital
  Gamma: "\\Gamma",
  Delta: "\\Delta",
  Theta: "\\Theta",
  Lambda: "\\Lambda",
  Xi: "\\Xi",
  Pi: "\\Pi",
  Sigma: "\\Sigma",
  Upsilon: "\\Upsilon",
  Phi: "\\Phi",
  Psi: "\\Psi",
  Omega: "\\Omega",
  // unit vectors
  uniti: "\\uniti",
  unitj: "\\unitj",
  unitk: "\\unitk",
  unitx: "\\unitx",
  unity: "\\unity",
  unitz: "\\unitz",
  // derivatives
  pdiff: "\\frac{\\partial #?}{\\partial #?}",
  diff: "\\frac{\\differentialD #?}{\\differentialD #?}",
  unitT: "\\operatorname{unitT}(#?, #?)",
  unitN: "\\operatorname{unitN}(#?, #?)",
  unitB: "\\operatorname{unitB}(#?, #?)",
  grad: "\\operatorname{grad}(#?)",
  // operators
  "*": " \\cdot",
};

export const extraMacros = {
  // unit vectors
  uniti: "\\hat{\\mathbf{i}}",
  unitj: "\\hat{\\mathbf{j}}",
  unitk: "\\hat{\\mathbf{k}}",
  unitx: "\\hat{\\mathbf{x}}",
  unity: "\\hat{\\mathbf{y}}",
  unitz: "\\hat{\\mathbf{z}}",
  // others
  abs: "\\operatorname{abs}",
};
