export const inlineShortcuts = {
  // trig
  sin: "\\sin",
  cos: "\\cos",
  tan: "\\tan",
  csc: "\\csc",
  sec: "\\sec",
  cot: "\\cot",
  // inverse trig
  arcsin: "\\arcsin",
  arccos: "\\arccos",
  arctan: "\\arctan",
  arccsc: "\\arccsc",
  arcsec: "\\arcsec",
  arccot: "\\arccot",
  // hyperbolic trig
  sinh: "\\sinh",
  cosh: "\\cosh",
  tanh: "\\tanh",
  csch: "\\csch",
  sech: "\\sech",
  coth: "\\coth",
  // inverse hyperbolic trig
  arcsinh: "\\arcsinh",
  arccosh: "\\arccosh",
  arctanh: "\\arctanh",
  arccsch: "\\arccsch",
  arcsech: "\\arcsech",
  arccoth: "\\arccoth",
  // sqrt
  sqrt: "\\sqrt{#?}",
  // exp
  exp: "\\exp",
  ln: "\\ln",
  log: "\\log",
  // greek
  alpha: "\\alpha",
  beta: "\\beta",
  gamma: "\\gamma",
  delta: "\\delta",
  epsilon: "\\epsilon",
  zeta: "\\zeta",
  eta: "\\eta",
  theta: "\\theta",
  iota: "\\iota",
  kappa: "\\kappa",
  lambda: "\\lambda",
  mu: "\\mu",
  nu: "\\nu",
  xi: "\\xi",
  omicron: "\\omicron",
  pi: "\\pi",
  rho: "\\rho",
  sigma: "\\sigma",
  tau: "\\tau",
  upsilon: "\\upsilon",
  phi: "\\phi",
  chi: "\\chi",
  psi: "\\psi",
  omega: "\\omega",
  // green, Capital
  Gamma: "\\Gamma",
  Delta: "\\Delta",
  Theta: "\\Theta",
  Lambda: "\\Lambda",
  Xi: "\\Xi",
  Pi: "\\Pi",
  Sigma: "\\Sigma",
  Upsilon: "\\Upsilon",
  Phi: "\\Phi",
  Psi: "\\Psi",
  Omega: "\\Omega",
  // derivatives
  pdiff: "\\frac{\\partial #?}{\\partial #?}",
  diff: "\\frac{\\differentialD #?}{\\differentialD #?}",
  // operators
  "*": "\\cdot",
};
