# Generated by Django 6.0.7 on 2026-08-31 01:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0006_drop_authtoken_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="public_nickname",
        ),
    ]
