# Generated by Django 6.0.7 on 2026-08-31 01:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0006_drop_authtoken_token"),
    ]

    operations = [
        # `blank`/`default` are Python-level, so this emits no forward DDL. It
        # exists for the reverse: re-adding a NOT NULL column with no default
        # fails on a table with rows, so `migrate authentication 0006` would
        # abort without it.
        migrations.AlterField(
            model_name="customuser",
            name="public_nickname",
            field=models.CharField(max_length=64, blank=True, default=""),
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="public_nickname",
        ),
    ]
