# Generated by Django 6.0.7 on 2026-08-31 01:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0006_drop_authtoken_token"),
    ]

    operations = [
        # `blank`/`default` are Python-level, so this emits no DDL: the column
        # stays for releases before ADR-0004, which a rollback runs.
        migrations.AlterField(
            model_name="customuser",
            name="public_nickname",
            field=models.CharField(max_length=64, blank=True, default=""),
        ),
    ]
