# Generated by Django 6.0.7 on 2026-09-29 11:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0007_customuser_public_nickname_unused"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="public_nickname",
        ),
    ]
