/* tslint:disable */
/* eslint-disable */
/**
 * django-allauth: Headless API
 * Trimmed django-allauth headless browser API. Vendored via `manage.py dump_openapi_allauth`.
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from "./configuration";
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from "axios";
import globalAxios from "axios";
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
  replaceWithSerializableTypeIfNeeded,
} from "./common";
import type { RequestArgs } from "./base";
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  BaseAPI,
  RequiredError,
  operationServerMap,
} from "./base";

export interface Authenticated {
  /**
   * A list of methods used to authenticate.
   */
  methods: Array<AuthenticationMethod>;
  user: User;
}
export interface AuthenticatedAfterPasswordReset {
  /**
   * An epoch based timestamp (trivial to parse using: `new Date(value)*1000`)
   */
  at: number;
  /**
   * The email address.
   */
  email: string;
  method: AuthenticatedAfterPasswordResetMethodEnum;
}

export const AuthenticatedAfterPasswordResetMethodEnum = {
  PasswordReset: "password_reset",
} as const;

export type AuthenticatedAfterPasswordResetMethodEnum =
  (typeof AuthenticatedAfterPasswordResetMethodEnum)[keyof typeof AuthenticatedAfterPasswordResetMethodEnum];

export interface AuthenticatedByConfirmingACodeSentByEmail {
  /**
   * An epoch based timestamp (trivial to parse using: `new Date(value)*1000`)
   */
  at: number;
  /**
   * The email address.
   */
  email: string;
  method: AuthenticatedByConfirmingACodeSentByEmailMethodEnum;
}

export const AuthenticatedByConfirmingACodeSentByEmailMethodEnum = {
  Code: "code",
} as const;

export type AuthenticatedByConfirmingACodeSentByEmailMethodEnum =
  (typeof AuthenticatedByConfirmingACodeSentByEmailMethodEnum)[keyof typeof AuthenticatedByConfirmingACodeSentByEmailMethodEnum];

export interface AuthenticatedByConfirmingACodeSentByPhone {
  /**
   * An epoch based timestamp (trivial to parse using: `new Date(value)*1000`)
   */
  at: number;
  method: AuthenticatedByConfirmingACodeSentByPhoneMethodEnum;
  /**
   * The phone number.
   */
  phone: string;
}

export const AuthenticatedByConfirmingACodeSentByPhoneMethodEnum = {
  Code: "code",
} as const;

export type AuthenticatedByConfirmingACodeSentByPhoneMethodEnum =
  (typeof AuthenticatedByConfirmingACodeSentByPhoneMethodEnum)[keyof typeof AuthenticatedByConfirmingACodeSentByPhoneMethodEnum];

export interface AuthenticatedByThirdPartyProvider {
  /**
   * An epoch based timestamp (trivial to parse using: `new Date(value)*1000`)
   */
  at: number;
  method: AuthenticatedByThirdPartyProviderMethodEnum;
  /**
   * The provider ID.
   */
  provider: string;
  /**
   * The provider specific account ID.
   */
  uid: string;
}

export const AuthenticatedByThirdPartyProviderMethodEnum = {
  Socialaccount: "socialaccount",
} as const;

export type AuthenticatedByThirdPartyProviderMethodEnum =
  (typeof AuthenticatedByThirdPartyProviderMethodEnum)[keyof typeof AuthenticatedByThirdPartyProviderMethodEnum];

export interface AuthenticatedByUsernameEmailLogin {
  /**
   * An epoch based timestamp (trivial to parse using: `new Date(value)*1000`)
   */
  at: number;
  /**
   * The email address.
   */
  email?: string;
  method: AuthenticatedByUsernameEmailLoginMethodEnum;
  /**
   * The username.
   */
  username?: string;
}

export const AuthenticatedByUsernameEmailLoginMethodEnum = {
  Password: "password",
} as const;

export type AuthenticatedByUsernameEmailLoginMethodEnum =
  (typeof AuthenticatedByUsernameEmailLoginMethodEnum)[keyof typeof AuthenticatedByUsernameEmailLoginMethodEnum];

export interface AuthenticatedResponse {
  data: Authenticated;
  meta: AuthenticationMeta;
  status: StatusOK;
}

export interface AuthenticationMeta {
  /**
   * The access token (`app` clients only).
   */
  access_token?: string;
  /**
   * The session token (`app` clients only).
   */
  session_token?: string;
  is_authenticated: boolean;
}
/**
 * @type AuthenticationMethod
 */
export type AuthenticationMethod =
  | AuthenticatedAfterPasswordReset
  | AuthenticatedByConfirmingACodeSentByEmail
  | AuthenticatedByConfirmingACodeSentByPhone
  | AuthenticatedByThirdPartyProvider
  | AuthenticatedByUsernameEmailLogin
  | ReAuthenticatedBy2FA
  | ReauthenticatedByPassword;

/**
 * An authentication related response.
 */
export interface AuthenticationResponse {
  data: AuthenticationResponseData;
  meta: AuthenticationMeta;
  status: AuthenticationResponseStatusEnum;
}

export const AuthenticationResponseStatusEnum = {
  NUMBER_401: 401,
} as const;

export type AuthenticationResponseStatusEnum =
  (typeof AuthenticationResponseStatusEnum)[keyof typeof AuthenticationResponseStatusEnum];

export interface AuthenticationResponseData {
  flows: Array<Flow>;
}
/**
 * The type of authenticator.
 */

export const AuthenticatorType = {
  RecoveryCodes: "recovery_codes",
  Totp: "totp",
  Webauthn: "webauthn",
} as const;

export type AuthenticatorType =
  (typeof AuthenticatorType)[keyof typeof AuthenticatorType];

export interface BaseAuthenticationMeta {
  /**
   * The access token (`app` clients only).
   */
  access_token?: string;
  /**
   * The session token (`app` clients only).
   */
  session_token?: string;
}
export interface BaseSignup {
  /**
   * The email address.
   */
  email: string;
  public_nickname?: string;
}
export interface ChangePasswordRequest {
  /**
   * The password.
   */
  current_password?: string;
  /**
   * The current password.
   */
  new_password: string;
}
export interface ConflictResponse {
  status: ConflictResponseStatusEnum;
}

export const ConflictResponseStatusEnum = {
  NUMBER_409: 409,
} as const;

export type ConflictResponseStatusEnum =
  (typeof ConflictResponseStatusEnum)[keyof typeof ConflictResponseStatusEnum];

export interface ErrorResponse {
  errors?: Array<ErrorResponseErrorsInner>;
  status?: ErrorResponseStatusEnum;
}

export const ErrorResponseStatusEnum = {
  NUMBER_400: 400,
} as const;

export type ErrorResponseStatusEnum =
  (typeof ErrorResponseStatusEnum)[keyof typeof ErrorResponseStatusEnum];

export interface ErrorResponseErrorsInner {
  /**
   * An error code.
   */
  code: string;
  /**
   * A human readable error message.
   */
  message: string;
  /**
   * The name of the input parameter that was incorrect.
   */
  param?: string;
}
export interface Flow {
  id: FlowIdEnum;
  is_pending?: boolean;
  provider?: Provider;
  /**
   * Matches `settings.MFA_SUPPORTED_TYPES`.
   */
  types?: Array<AuthenticatorType>;
}

export const FlowIdEnum = {
  Login: "login",
  LoginByCode: "login_by_code",
  MfaAuthenticate: "mfa_authenticate",
  MfaReauthenticate: "mfa_reauthenticate",
  ProviderRedirect: "provider_redirect",
  ProviderSignup: "provider_signup",
  ProviderToken: "provider_token",
  Reauthenticate: "reauthenticate",
  Signup: "signup",
  VerifyEmail: "verify_email",
  VerifyPhone: "verify_phone",
} as const;

export type FlowIdEnum = (typeof FlowIdEnum)[keyof typeof FlowIdEnum];

export interface ForbiddenResponse {
  status: ForbiddenResponseStatusEnum;
}

export const ForbiddenResponseStatusEnum = {
  NUMBER_403: 403,
} as const;

export type ForbiddenResponseStatusEnum =
  (typeof ForbiddenResponseStatusEnum)[keyof typeof ForbiddenResponseStatusEnum];

export interface Login {
  /**
   * The email address.
   */
  email: string;
  /**
   * The password.
   */
  password: string;
}
export interface Provider {
  /**
   * The client ID (in case of OAuth2 or OpenID Connect based providers)
   */
  client_id?: string;
  /**
   * The authentication flows the provider integration supports.
   */
  flows: Array<ProviderFlowsEnum>;
  /**
   * The provider ID.
   */
  id: string;
  /**
   * The name of the provider.
   */
  name: string;
  /**
   * The OIDC discovery or well-known URL (in case of OAuth2 or OpenID Connect based providers)
   */
  openid_configuration_url?: string;
}

export const ProviderFlowsEnum = {
  ProviderRedirect: "provider_redirect",
  ProviderToken: "provider_token",
} as const;

export type ProviderFlowsEnum =
  (typeof ProviderFlowsEnum)[keyof typeof ProviderFlowsEnum];

export interface ReAuthenticatedBy2FA {
  /**
   * An epoch based timestamp (trivial to parse using: `new Date(value)*1000`)
   */
  at: number;
  method: ReAuthenticatedBy2FAMethodEnum;
  reauthenticated?: boolean;
  type: AuthenticatorType;
}

export const ReAuthenticatedBy2FAMethodEnum = {
  Mfa: "mfa",
} as const;

export type ReAuthenticatedBy2FAMethodEnum =
  (typeof ReAuthenticatedBy2FAMethodEnum)[keyof typeof ReAuthenticatedBy2FAMethodEnum];

export interface ReauthenticatedByPassword {
  /**
   * An epoch based timestamp (trivial to parse using: `new Date(value)*1000`)
   */
  at: number;
  method: ReauthenticatedByPasswordMethodEnum;
  reauthenticated: boolean;
}

export const ReauthenticatedByPasswordMethodEnum = {
  Password: "password",
} as const;

export type ReauthenticatedByPasswordMethodEnum =
  (typeof ReauthenticatedByPasswordMethodEnum)[keyof typeof ReauthenticatedByPasswordMethodEnum];

export interface RequestPassword {
  /**
   * The email address.
   */
  email: string;
}
export interface RequestPassword200Response {
  status: StatusOK;
}

export interface ResetPassword {
  /**
   * The password reset key
   */
  key: string;
  /**
   * The password.
   */
  password: string;
}
export interface Signup {
  /**
   * The email address.
   */
  email: string;
  public_nickname?: string;
  /**
   * The password.
   */
  password: string;
}

export const StatusOK = {
  NUMBER_200: 200,
} as const;

export type StatusOK = (typeof StatusOK)[keyof typeof StatusOK];

export interface User {
  /**
   * The display name for the user.
   */
  display: string;
  /**
   * The email address.
   */
  email?: string;
  /**
   * Whether or not the account has a password set.
   */
  has_usable_password: boolean;
  /**
   * The user ID.
   */
  id?: number;
}
export interface VerifyEmail {
  /**
   * The email verification key
   */
  key: string;
}

/**
 * AllauthApi - axios parameter creator
 */
export const AllauthApiAxiosParamCreator = function (
  configuration?: Configuration,
) {
  return {
    /**
     * In order to change the password of an account, the current and new password must be provider.  However, accounts that were created by signing up using a third-party provider do not have a password set. In that case, the current password is not required.
     * @summary Change password
     * @param {ChangePasswordRequest} [ChangePasswordRequest]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    changePassword: async (
      ChangePasswordRequest?: ChangePasswordRequest,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/_allauth/browser/v1/account/password/change`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Content-Type"] = "application/json";
      localVarHeaderParameter["Accept"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        ChangePasswordRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Login using a username-password or email-password combination.
     * @summary Login
     * @param {Login} Login Login.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    login: async (
      Login: Login,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'Login' is not null or undefined
      assertParamExists("login", "Login", Login);
      const localVarPath = `/_allauth/browser/v1/auth/login`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Content-Type"] = "application/json";
      localVarHeaderParameter["Accept"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        Login,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Logs out the user from the current session.
     * @summary Logout
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    logout: async (
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/_allauth/browser/v1/auth/session`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "DELETE",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Accept"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Initiates the password reset procedure. Depending on whether or not `ACCOUNT_PASSWORD_RESET_BY_CODE_ENABLED` is `True`, the procedure is either stateless or stateful.  In case codes are used, it is stateful, and a new `password_reset_by_code` flow is started. In this case, on a successful password reset request, you will receive a 401 indicating the pending status of this flow.  In case password reset is configured to use (stateless) links, you will receive a 200 on a successful password reset request.
     * @summary Request password
     * @param {RequestPassword} RequestPassword Request password.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    requestPassword: async (
      RequestPassword: RequestPassword,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'RequestPassword' is not null or undefined
      assertParamExists("requestPassword", "RequestPassword", RequestPassword);
      const localVarPath = `/_allauth/browser/v1/auth/password/request`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Content-Type"] = "application/json";
      localVarHeaderParameter["Accept"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        RequestPassword,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Perform the password reset, by handing over the password reset key and the new password. After successfully completing the password reset, the user is either logged in (in case `ACCOUNT_LOGIN_ON_PASSWORD_RESET` is `True`), or, the user will need to proceed to the login page.  In case of the former, a `200` status code is returned, in case of the latter a 401.
     * @summary Reset password
     * @param {ResetPassword} [ResetPassword]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    resetPassword: async (
      ResetPassword?: ResetPassword,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/_allauth/browser/v1/auth/password/reset`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Content-Type"] = "application/json";
      localVarHeaderParameter["Accept"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        ResetPassword,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Whether or not `username`, `email`, `phone` or combination of those are required depends on the configuration of django-allauth. Additionally, if a custom signup form is used there may be other custom properties required.
     * @summary Signup
     * @param {Signup} Signup Signup
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    signup: async (
      Signup: Signup,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'Signup' is not null or undefined
      assertParamExists("signup", "Signup", Signup);
      const localVarPath = `/_allauth/browser/v1/auth/signup`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Content-Type"] = "application/json";
      localVarHeaderParameter["Accept"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        Signup,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Complete the email verification process. Depending on the configuration, email addresses are either verified by opening a link that is sent to their email address, or, by inputting a code that is sent. On the API, both cases are handled identically. Meaning, the required key is either the one from the link, or, the code itself.  Note that a status code of 401 does not imply failure. It indicates that the email verification was successful, yet, the user is still not signed in. For example, in case `ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION` is set to `False`, a 401 is returned when verifying as part of login/signup.
     * @summary Verify an email
     * @param {VerifyEmail} [VerifyEmail]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    verifyEmail: async (
      VerifyEmail?: VerifyEmail,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/_allauth/browser/v1/auth/email/verify`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Content-Type"] = "application/json";
      localVarHeaderParameter["Accept"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        VerifyEmail,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * AllauthApi - functional programming interface
 */
export const AllauthApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = AllauthApiAxiosParamCreator(configuration);
  return {
    /**
     * In order to change the password of an account, the current and new password must be provider.  However, accounts that were created by signing up using a third-party provider do not have a password set. In that case, the current password is not required.
     * @summary Change password
     * @param {ChangePasswordRequest} [ChangePasswordRequest]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async changePassword(
      ChangePasswordRequest?: ChangePasswordRequest,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.changePassword(
        ChangePasswordRequest,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["AllauthApi.changePassword"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Login using a username-password or email-password combination.
     * @summary Login
     * @param {Login} Login Login.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async login(
      Login: Login,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<AuthenticatedResponse>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.login(
        Login,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["AllauthApi.login"]?.[localVarOperationServerIndex]
          ?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Logs out the user from the current session.
     * @summary Logout
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async logout(
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.logout(options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["AllauthApi.logout"]?.[localVarOperationServerIndex]
          ?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Initiates the password reset procedure. Depending on whether or not `ACCOUNT_PASSWORD_RESET_BY_CODE_ENABLED` is `True`, the procedure is either stateless or stateful.  In case codes are used, it is stateful, and a new `password_reset_by_code` flow is started. In this case, on a successful password reset request, you will receive a 401 indicating the pending status of this flow.  In case password reset is configured to use (stateless) links, you will receive a 200 on a successful password reset request.
     * @summary Request password
     * @param {RequestPassword} RequestPassword Request password.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async requestPassword(
      RequestPassword: RequestPassword,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<RequestPassword200Response>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.requestPassword(
        RequestPassword,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["AllauthApi.requestPassword"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Perform the password reset, by handing over the password reset key and the new password. After successfully completing the password reset, the user is either logged in (in case `ACCOUNT_LOGIN_ON_PASSWORD_RESET` is `True`), or, the user will need to proceed to the login page.  In case of the former, a `200` status code is returned, in case of the latter a 401.
     * @summary Reset password
     * @param {ResetPassword} [ResetPassword]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async resetPassword(
      ResetPassword?: ResetPassword,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<AuthenticatedResponse>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.resetPassword(
        ResetPassword,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["AllauthApi.resetPassword"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Whether or not `username`, `email`, `phone` or combination of those are required depends on the configuration of django-allauth. Additionally, if a custom signup form is used there may be other custom properties required.
     * @summary Signup
     * @param {Signup} Signup Signup
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async signup(
      Signup: Signup,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<AuthenticatedResponse>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.signup(
        Signup,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["AllauthApi.signup"]?.[localVarOperationServerIndex]
          ?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Complete the email verification process. Depending on the configuration, email addresses are either verified by opening a link that is sent to their email address, or, by inputting a code that is sent. On the API, both cases are handled identically. Meaning, the required key is either the one from the link, or, the code itself.  Note that a status code of 401 does not imply failure. It indicates that the email verification was successful, yet, the user is still not signed in. For example, in case `ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION` is set to `False`, a 401 is returned when verifying as part of login/signup.
     * @summary Verify an email
     * @param {VerifyEmail} [VerifyEmail]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async verifyEmail(
      VerifyEmail?: VerifyEmail,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<AuthenticatedResponse>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.verifyEmail(
        VerifyEmail,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["AllauthApi.verifyEmail"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
  };
};

/**
 * AllauthApi - factory interface
 */
export const AllauthApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = AllauthApiFp(configuration);
  return {
    /**
     * In order to change the password of an account, the current and new password must be provider.  However, accounts that were created by signing up using a third-party provider do not have a password set. In that case, the current password is not required.
     * @summary Change password
     * @param {AllauthApiChangePasswordRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    changePassword(
      requestParameters: AllauthApiChangePasswordRequest = {},
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<void> {
      return localVarFp
        .changePassword(requestParameters.ChangePasswordRequest, options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Login using a username-password or email-password combination.
     * @summary Login
     * @param {AllauthApiLoginRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    login(
      requestParameters: AllauthApiLoginRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<AuthenticatedResponse> {
      return localVarFp
        .login(requestParameters.Login, options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Logs out the user from the current session.
     * @summary Logout
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    logout(options?: RawAxiosRequestConfig): AxiosPromise<void> {
      return localVarFp
        .logout(options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Initiates the password reset procedure. Depending on whether or not `ACCOUNT_PASSWORD_RESET_BY_CODE_ENABLED` is `True`, the procedure is either stateless or stateful.  In case codes are used, it is stateful, and a new `password_reset_by_code` flow is started. In this case, on a successful password reset request, you will receive a 401 indicating the pending status of this flow.  In case password reset is configured to use (stateless) links, you will receive a 200 on a successful password reset request.
     * @summary Request password
     * @param {AllauthApiRequestPasswordRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    requestPassword(
      requestParameters: AllauthApiRequestPasswordRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<RequestPassword200Response> {
      return localVarFp
        .requestPassword(requestParameters.RequestPassword, options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Perform the password reset, by handing over the password reset key and the new password. After successfully completing the password reset, the user is either logged in (in case `ACCOUNT_LOGIN_ON_PASSWORD_RESET` is `True`), or, the user will need to proceed to the login page.  In case of the former, a `200` status code is returned, in case of the latter a 401.
     * @summary Reset password
     * @param {AllauthApiResetPasswordRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    resetPassword(
      requestParameters: AllauthApiResetPasswordRequest = {},
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<AuthenticatedResponse> {
      return localVarFp
        .resetPassword(requestParameters.ResetPassword, options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Whether or not `username`, `email`, `phone` or combination of those are required depends on the configuration of django-allauth. Additionally, if a custom signup form is used there may be other custom properties required.
     * @summary Signup
     * @param {AllauthApiSignupRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    signup(
      requestParameters: AllauthApiSignupRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<AuthenticatedResponse> {
      return localVarFp
        .signup(requestParameters.Signup, options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Complete the email verification process. Depending on the configuration, email addresses are either verified by opening a link that is sent to their email address, or, by inputting a code that is sent. On the API, both cases are handled identically. Meaning, the required key is either the one from the link, or, the code itself.  Note that a status code of 401 does not imply failure. It indicates that the email verification was successful, yet, the user is still not signed in. For example, in case `ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION` is set to `False`, a 401 is returned when verifying as part of login/signup.
     * @summary Verify an email
     * @param {AllauthApiVerifyEmailRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    verifyEmail(
      requestParameters: AllauthApiVerifyEmailRequest = {},
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<AuthenticatedResponse> {
      return localVarFp
        .verifyEmail(requestParameters.VerifyEmail, options)
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * Request parameters for changePassword operation in AllauthApi.
 */
export interface AllauthApiChangePasswordRequest {
  readonly ChangePasswordRequest?: ChangePasswordRequest;
}

/**
 * Request parameters for login operation in AllauthApi.
 */
export interface AllauthApiLoginRequest {
  /**
   * Login.
   */
  readonly Login: Login;
}

/**
 * Request parameters for requestPassword operation in AllauthApi.
 */
export interface AllauthApiRequestPasswordRequest {
  /**
   * Request password.
   */
  readonly RequestPassword: RequestPassword;
}

/**
 * Request parameters for resetPassword operation in AllauthApi.
 */
export interface AllauthApiResetPasswordRequest {
  readonly ResetPassword?: ResetPassword;
}

/**
 * Request parameters for signup operation in AllauthApi.
 */
export interface AllauthApiSignupRequest {
  /**
   * Signup
   */
  readonly Signup: Signup;
}

/**
 * Request parameters for verifyEmail operation in AllauthApi.
 */
export interface AllauthApiVerifyEmailRequest {
  readonly VerifyEmail?: VerifyEmail;
}

/**
 * AllauthApi - object-oriented interface
 */
export class AllauthApi extends BaseAPI {
  /**
   * In order to change the password of an account, the current and new password must be provider.  However, accounts that were created by signing up using a third-party provider do not have a password set. In that case, the current password is not required.
   * @summary Change password
   * @param {AllauthApiChangePasswordRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public changePassword(
    requestParameters: AllauthApiChangePasswordRequest = {},
    options?: RawAxiosRequestConfig,
  ) {
    return AllauthApiFp(this.configuration)
      .changePassword(requestParameters.ChangePasswordRequest, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Login using a username-password or email-password combination.
   * @summary Login
   * @param {AllauthApiLoginRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public login(
    requestParameters: AllauthApiLoginRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return AllauthApiFp(this.configuration)
      .login(requestParameters.Login, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Logs out the user from the current session.
   * @summary Logout
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public logout(options?: RawAxiosRequestConfig) {
    return AllauthApiFp(this.configuration)
      .logout(options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Initiates the password reset procedure. Depending on whether or not `ACCOUNT_PASSWORD_RESET_BY_CODE_ENABLED` is `True`, the procedure is either stateless or stateful.  In case codes are used, it is stateful, and a new `password_reset_by_code` flow is started. In this case, on a successful password reset request, you will receive a 401 indicating the pending status of this flow.  In case password reset is configured to use (stateless) links, you will receive a 200 on a successful password reset request.
   * @summary Request password
   * @param {AllauthApiRequestPasswordRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public requestPassword(
    requestParameters: AllauthApiRequestPasswordRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return AllauthApiFp(this.configuration)
      .requestPassword(requestParameters.RequestPassword, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Perform the password reset, by handing over the password reset key and the new password. After successfully completing the password reset, the user is either logged in (in case `ACCOUNT_LOGIN_ON_PASSWORD_RESET` is `True`), or, the user will need to proceed to the login page.  In case of the former, a `200` status code is returned, in case of the latter a 401.
   * @summary Reset password
   * @param {AllauthApiResetPasswordRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public resetPassword(
    requestParameters: AllauthApiResetPasswordRequest = {},
    options?: RawAxiosRequestConfig,
  ) {
    return AllauthApiFp(this.configuration)
      .resetPassword(requestParameters.ResetPassword, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Whether or not `username`, `email`, `phone` or combination of those are required depends on the configuration of django-allauth. Additionally, if a custom signup form is used there may be other custom properties required.
   * @summary Signup
   * @param {AllauthApiSignupRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public signup(
    requestParameters: AllauthApiSignupRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return AllauthApiFp(this.configuration)
      .signup(requestParameters.Signup, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Complete the email verification process. Depending on the configuration, email addresses are either verified by opening a link that is sent to their email address, or, by inputting a code that is sent. On the API, both cases are handled identically. Meaning, the required key is either the one from the link, or, the code itself.  Note that a status code of 401 does not imply failure. It indicates that the email verification was successful, yet, the user is still not signed in. For example, in case `ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION` is set to `False`, a 401 is returned when verifying as part of login/signup.
   * @summary Verify an email
   * @param {AllauthApiVerifyEmailRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public verifyEmail(
    requestParameters: AllauthApiVerifyEmailRequest = {},
    options?: RawAxiosRequestConfig,
  ) {
    return AllauthApiFp(this.configuration)
      .verifyEmail(requestParameters.VerifyEmail, options)
      .then((request) => request(this.axios, this.basePath));
  }
}
