/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/_allauth/browser/v1/auth/session": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Logout
     * @description Logs out the user from the current session.
     */
    delete: operations["logout"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    AuthenticationMeta: components["schemas"]["BaseAuthenticationMeta"] & {
      is_authenticated: boolean;
    };
    /** @description An authentication related response. */
    AuthenticationResponse: {
      data: {
        flows: components["schemas"]["Flow"][];
      };
      meta: components["schemas"]["AuthenticationMeta"];
      /** @enum {integer} */
      status: 401;
    };
    /**
     * @description The type of authenticator.
     * @enum {string}
     */
    AuthenticatorType: "recovery_codes" | "totp" | "webauthn";
    BaseAuthenticationMeta: {
      /** @description The access token (`app` clients only). */
      access_token?: string;
      /** @description The session token (`app` clients only). */
      session_token?: string;
    };
    Flow: {
      /** @enum {string} */
      id:
        | "login"
        | "login_by_code"
        | "mfa_authenticate"
        | "mfa_reauthenticate"
        | "provider_redirect"
        | "provider_signup"
        | "provider_token"
        | "reauthenticate"
        | "signup"
        | "verify_email"
        | "verify_phone";
      /** @enum {boolean} */
      is_pending?: true;
      provider?: components["schemas"]["Provider"];
      /** @description Matches `settings.MFA_SUPPORTED_TYPES`. */
      types?: components["schemas"]["AuthenticatorType"][];
    };
    Provider: {
      /** @description The client ID (in case of OAuth2 or OpenID Connect based providers) */
      client_id?: string;
      /** @description The authentication flows the provider integration supports. */
      flows: ("provider_redirect" | "provider_token")[];
      /** @description The provider ID. */
      id: string;
      /** @description The name of the provider. */
      name: string;
      /** @description The OIDC discovery or well-known URL (in case of OAuth2 or OpenID Connect based providers) */
      openid_configuration_url?: string;
    };
  };
  responses: {
    /** @description There is no authenticated session. */
    Unauthenticated: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["AuthenticationResponse"];
      };
    };
  };
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      401: components["responses"]["Unauthenticated"];
    };
  };
}
