/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/_allauth/browser/v1/account/password/change": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Change password
     * @description In order to change the password of an account, the current and new
     *     password must be provider.  However, accounts that were created by
     *     signing up using a third-party provider do not have a password set. In
     *     that case, the current password is not required.
     */
    post: operations["changePassword"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/_allauth/browser/v1/auth/email/verify": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Verify an email
     * @description Complete the email verification process. Depending on the configuration,
     *     email addresses are either verified by opening a link that is sent to
     *     their email address, or, by inputting a code that is sent. On the API,
     *     both cases are handled identically. Meaning, the required key is either
     *     the one from the link, or, the code itself.
     *
     *     Note that a status code of 401 does not imply failure. It indicates that
     *     the email verification was successful, yet, the user is still not signed
     *     in. For example, in case `ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION` is set to
     *     `False`, a 401 is returned when verifying as part of login/signup.
     */
    post: operations["verifyEmail"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/_allauth/browser/v1/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Login
     * @description Login using a username-password or email-password combination.
     */
    post: operations["login"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/_allauth/browser/v1/auth/password/request": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Request password
     * @description Initiates the password reset procedure. Depending on whether or not
     *     `ACCOUNT_PASSWORD_RESET_BY_CODE_ENABLED` is `True`, the procedure is
     *     either stateless or stateful.
     *
     *     In case codes are used, it is stateful, and a new
     *     `password_reset_by_code` flow is started. In this case, on a successful
     *     password reset request, you will receive a 401 indicating the pending
     *     status of this flow.
     *
     *     In case password reset is configured to use (stateless) links, you will
     *     receive a 200 on a successful password reset request.
     */
    post: operations["requestPassword"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/_allauth/browser/v1/auth/password/reset": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Reset password
     * @description Perform the password reset, by handing over the password reset key and
     *     the new password. After successfully completing the password reset, the
     *     user is either logged in (in case `ACCOUNT_LOGIN_ON_PASSWORD_RESET` is
     *     `True`), or, the user will need to proceed to the login page.  In case
     *     of the former, a `200` status code is returned, in case of the latter a
     *     401.
     */
    post: operations["resetPassword"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/_allauth/browser/v1/auth/session": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Logout
     * @description Logs out the user from the current session.
     */
    delete: operations["logout"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/_allauth/browser/v1/auth/signup": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Signup
     * @description Whether or not `username`, `email`, `phone` or combination of those are
     *     required depends on the configuration of django-allauth. Additionally,
     *     if a custom signup form is used there may be other custom properties
     *     required.
     */
    post: operations["signup"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Authenticated: {
      /** @description A list of methods used to authenticate. */
      methods: components["schemas"]["AuthenticationMethod"][];
      user: components["schemas"]["User"];
    };
    AuthenticatedResponse: {
      data: components["schemas"]["Authenticated"];
      meta: components["schemas"]["AuthenticationMeta"];
      status: components["schemas"]["StatusOK"];
    };
    AuthenticationMeta: components["schemas"]["BaseAuthenticationMeta"] & {
      is_authenticated: boolean;
    };
    AuthenticationMethod:
      | {
          at: components["schemas"]["Timestamp"];
          email?: components["schemas"]["Email"];
          /** @enum {string} */
          method: "password";
          username?: components["schemas"]["Username"];
        }
      | {
          at: components["schemas"]["Timestamp"];
          email: components["schemas"]["Email"];
          /** @enum {string} */
          method: "password_reset";
        }
      | {
          at: components["schemas"]["Timestamp"];
          email: components["schemas"]["Email"];
          /** @enum {string} */
          method: "code";
        }
      | {
          at: components["schemas"]["Timestamp"];
          /** @enum {string} */
          method: "code";
          phone: components["schemas"]["Phone"];
        }
      | {
          at: components["schemas"]["Timestamp"];
          /** @enum {string} */
          method: "password";
          /** @enum {boolean} */
          reauthenticated: true;
        }
      | {
          at: components["schemas"]["Timestamp"];
          /** @enum {string} */
          method: "socialaccount";
          provider: components["schemas"]["ProviderID"];
          uid: components["schemas"]["ProviderAccountID"];
        }
      | {
          at: components["schemas"]["Timestamp"];
          /** @enum {string} */
          method: "mfa";
          reauthenticated?: boolean;
          type: components["schemas"]["AuthenticatorType"];
        };
    /** @description An authentication related response. */
    AuthenticationResponse: {
      data: {
        flows: components["schemas"]["Flow"][];
      };
      meta: components["schemas"]["AuthenticationMeta"];
      /** @enum {integer} */
      status: 401;
    };
    /**
     * @description The type of authenticator.
     * @enum {string}
     */
    AuthenticatorType: "recovery_codes" | "totp" | "webauthn";
    BaseAuthenticationMeta: {
      /** @description The access token (`app` clients only). */
      access_token?: string;
      /** @description The session token (`app` clients only). */
      session_token?: string;
    };
    BaseSignup: {
      email: components["schemas"]["Email"];
      public_nickname?: string;
    };
    ConflictResponse: {
      /** @enum {integer} */
      status: 409;
    };
    /** @description The email address. */
    Email: string;
    ErrorResponse: {
      errors?: {
        /** @description An error code. */
        code: string;
        /** @description A human readable error message. */
        message: string;
        /** @description The name of the input parameter that was incorrect. */
        param?: string;
      }[];
      /** @enum {integer} */
      status?: 400;
    };
    Flow: {
      /** @enum {string} */
      id:
        | "login"
        | "login_by_code"
        | "mfa_authenticate"
        | "mfa_reauthenticate"
        | "provider_redirect"
        | "provider_signup"
        | "provider_token"
        | "reauthenticate"
        | "signup"
        | "verify_email"
        | "verify_phone";
      /** @enum {boolean} */
      is_pending?: true;
      provider?: components["schemas"]["Provider"];
      /** @description Matches `settings.MFA_SUPPORTED_TYPES`. */
      types?: components["schemas"]["AuthenticatorType"][];
    };
    ForbiddenResponse: {
      /** @enum {integer} */
      status: 403;
    };
    Login: {
      password: components["schemas"]["Password"];
    } & (
      | {
          username: components["schemas"]["Username"];
        }
      | {
          email: components["schemas"]["Email"];
        }
      | {
          phone: components["schemas"]["Phone"];
        }
    );
    /** @description The password. */
    Password: string;
    /** @description The phone number. */
    Phone: string;
    Provider: {
      /** @description The client ID (in case of OAuth2 or OpenID Connect based providers) */
      client_id?: string;
      /** @description The authentication flows the provider integration supports. */
      flows: ("provider_redirect" | "provider_token")[];
      /** @description The provider ID. */
      id: string;
      /** @description The name of the provider. */
      name: string;
      /** @description The OIDC discovery or well-known URL (in case of OAuth2 or OpenID Connect based providers) */
      openid_configuration_url?: string;
    };
    /** @description The provider specific account ID. */
    ProviderAccountID: string;
    /** @description The provider ID. */
    ProviderID: string;
    RequestPassword: {
      email: components["schemas"]["Email"];
    };
    ResetPassword: {
      /** @description The password reset key */
      key: string;
      password: components["schemas"]["Password"];
    };
    Signup: components["schemas"]["BaseSignup"] & {
      password: components["schemas"]["Password"];
    };
    /** @enum {integer} */
    StatusOK: 200;
    /** @description An epoch based timestamp (trivial to parse using: `new Date(value)*1000`) */
    Timestamp: number;
    User: {
      /** @description The display name for the user. */
      display: string;
      /** @description The email address. */
      email?: string;
      /** @description Whether or not the account has a password set. */
      has_usable_password: boolean;
      /** @description The user ID. */
      id?: number;
    };
    /** @description The username. */
    Username: string;
    VerifyEmail: {
      /** @description The email verification key */
      key: string;
    };
  };
  responses: {
    /** @description The user is authenticated. */
    Authenticated: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["AuthenticatedResponse"];
      };
    };
    /** @description Authenticated by password. */
    AuthenticatedByPassword: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["AuthenticatedResponse"];
      };
    };
    /** @description Not authenticated. */
    Authentication: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["AuthenticationResponse"];
      };
    };
    /** @description An input error occurred. */
    Error: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["ErrorResponse"];
      };
    };
    /** @description A success response. */
    StatusOK: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": {
          status: components["schemas"]["StatusOK"];
        };
      };
    };
    /** @description There is no authenticated session. */
    Unauthenticated: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["AuthenticationResponse"];
      };
    };
  };
  parameters: never;
  requestBodies: {
    ChangePassword: {
      content: {
        "application/json": {
          current_password?: components["schemas"]["Password"];
          /** @description The current password. */
          new_password: string;
        };
      };
    };
    /** @description Login. */
    Login: {
      content: {
        "application/json": components["schemas"]["Login"];
      };
    };
    /** @description Request password. */
    RequestPassword: {
      content: {
        "application/json": components["schemas"]["RequestPassword"];
      };
    };
    ResetPassword: {
      content: {
        "application/json": components["schemas"]["ResetPassword"];
      };
    };
    /** @description Signup */
    Signup: {
      content: {
        "application/json": components["schemas"]["Signup"];
      };
    };
    VerifyEmail: {
      content: {
        "application/json": components["schemas"]["VerifyEmail"];
      };
    };
  };
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  changePassword: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: components["requestBodies"]["ChangePassword"];
    responses: {
      400: components["responses"]["Error"];
      401: components["responses"]["Authentication"];
    };
  };
  verifyEmail: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: components["requestBodies"]["VerifyEmail"];
    responses: {
      200: components["responses"]["Authenticated"];
      /** @description An input error occurred. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      401: components["responses"]["Unauthenticated"];
      /** @description Conflict. The email verification (by code) flow is not pending. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConflictResponse"];
        };
      };
    };
  };
  login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: components["requestBodies"]["Login"];
    responses: {
      200: components["responses"]["AuthenticatedByPassword"];
      /** @description An input error occurred. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not authenticated. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthenticationResponse"];
        };
      };
      /** @description Conflict. For example, when logging in when a user is already logged in. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConflictResponse"];
        };
      };
    };
  };
  requestPassword: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: components["requestBodies"]["RequestPassword"];
    responses: {
      200: components["responses"]["StatusOK"];
      /** @description An input error occurred. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      401: components["responses"]["Authentication"];
    };
  };
  resetPassword: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: components["requestBodies"]["ResetPassword"];
    responses: {
      200: components["responses"]["AuthenticatedByPassword"];
      /** @description An input error occurred. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      401: components["responses"]["Authentication"];
      /** @description Conflict. There is no password reset (by code) flow pending. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConflictResponse"];
        };
      };
    };
  };
  logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      401: components["responses"]["Unauthenticated"];
    };
  };
  signup: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: components["requestBodies"]["Signup"];
    responses: {
      200: components["responses"]["AuthenticatedByPassword"];
      /** @description An input error occurred. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not authenticated. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthenticationResponse"];
        };
      };
      /** @description Forbidden. For example, when signup is closed. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ForbiddenResponse"];
        };
      };
      /** @description Conflict. For example, when signing up while user is logged in. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConflictResponse"];
        };
      };
    };
  };
}
