name: End-to-end Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CI: True

jobs:
  e2e-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    environment: "ci"
    env:
      SKIP_YARN_COREPACK_CHECK: true
      VITE_API_BASE_URL: ${{ vars.TEST_API_URL }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.11.1"
          cache: "yarn"
      - run: corepack enable
      - name: Setup env variables
        run: cp .env.development .env
      - name: Build docker stack
        run: docker compose build
      - name: Migrate backend database
        run: docker compose run --rm webserver ./manage.py migrate
      - name: Seed database
        run: docker compose run --rm webserver ./manage.py seed_test_data
      - name: Start docker stack
        run: docker compose up -d
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build and Start Frontend
        run: yarn build && yarn preview &
      - name: Install Playwright Browsers
        run: yarn workspace app-tests-e2e playwright install --with-deps
      - name: Run Playwright tests
        run: yarn test-e2e
        env:
          CI: True
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: packages/app-tests-e2e/playwright-report/
          retention-days: 30
