name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CI: True

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: "17.9.1"
        cache: "npm"
        cache-dependency-path: client/package-lock.json
    - name: Install dependencies
      run: npm ci
      working-directory: client
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      working-directory: client
    - name: Run Playwright tests
      run: npx playwright test
      env:
        CI: True
      working-directory: client
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
