name: Deploy

concurrency: production

on:
  workflow_dispatch

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
        AWS_S3_BUCKET: ${{ vars.AWS_S3_BUCKET }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.12.1"
          cache: "yarn"
      - run: yarn install --immutable
      - run: yarn build
      - run: aws s3 cp packages/app/dist s3://${{ vars.AWS_S3_BUCKET }}